# Generated by Django 5.1.2 on 2025-06-03 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membership", "0006_churchservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "poster_image",
                    models.ImageField(null=True, upload_to="event_posters"),
                ),
                ("description", models.TextField(null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Paid Event", "Paid Event"),
                            ("Free Event", "Free Event"),
                        ],
                        max_length=255,
                    ),
                ),
                ("starts_on", models.DateTimeField()),
                ("ends_on", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("checkin_time", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.churchevent",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membership.member",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
