# Generated by Django 5.2.5 on 2025-09-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventattendance",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="membership.member"
            ),
        ),
    ]
