# Generated by Django 5.2.5 on 2025-10-12 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_eventattendance_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="churchevent",
            name="closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="churchevent",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="churcheventtickettype",
            name="purchased",
            field=models.IntegerField(default=0),
        ),
    ]
