# Generated by Django 5.2.5 on 2025-10-12 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_churchevent_closed_churchevent_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="churcheventticket",
            name="member",
        ),
        migrations.RemoveField(
            model_name="eventattendance",
            name="member",
        ),
        migrations.AddField(
            model_name="churcheventticket",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="churcheventticket",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="churcheventticket",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="churcheventticket",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventattendance",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.churcheventticket",
            ),
        ),
        migrations.AlterField(
            model_name="churcheventticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventtickets",
                to="events.churchevent",
            ),
        ),
        migrations.AlterField(
            model_name="churcheventtickettype",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventtickettypes",
                to="events.churchevent",
            ),
        ),
        migrations.AlterField(
            model_name="eventattendance",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventattendances",
                to="events.churchevent",
            ),
        ),
    ]
