# Generated by Django 5.2.5 on 2025-10-12 11:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_churcheventticket_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="churcheventticket",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
    ]
