# Generated by Django 5.2.5 on 2025-10-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_churcheventticket_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="churcheventticket",
            name="ticket_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
