# Generated by Django 5.2.5 on 2025-10-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_churchmeeting_churchmeetingattendance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="churchmeetingattendance",
            name="meeting",
        ),
        migrations.RemoveField(
            model_name="churchmeetingattendance",
            name="member",
        ),
        migrations.RemoveField(
            model_name="churchmeetingattendance",
            name="recorded_by",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="ChurchMeeting",
        ),
        migrations.DeleteModel(
            name="ChurchMeetingAttendance",
        ),
    ]
