# Generated by Django 5.2.5 on 2025-10-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_remove_churchmeetingattendance_meeting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="churcheventticket",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
