# Generated by Django 5.2.5 on 2025-10-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_churcheventticket_used"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="churcheventticket",
            name="used",
        ),
        migrations.AddField(
            model_name="churcheventticket",
            name="status",
            field=models.CharField(
                choices=[("Used", "Used"), ("Unused", "Unused")],
                default="Unused",
                max_length=255,
            ),
        ),
    ]
