# Generated by Django 5.2.5 on 2025-10-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_remove_churcheventticket_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="churcheventticket",
            name="paid_status",
            field=models.CharField(
                choices=[
                    ("Paid", "Paid"),
                    ("Unpaid", "Unpaid"),
                    ("Partial", "Partial"),
                ],
                default="Unpaid",
                max_length=255,
            ),
        ),
    ]
