# Generated by Django 5.2.5 on 2025-10-27 19:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_churcheventticket_paid_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTicketPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("Card", "Card"),
                            ("Mobile Money", "Mobile Money"),
                        ],
                        default="Cash",
                        max_length=255,
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticketpayments",
                        to="events.churcheventticket",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
