# Generated by Django 5.2.5 on 2025-10-27 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_churchofferingchannel"),
        ("events", "0014_eventticketpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventticketpayment",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.churchofferingchannel",
            ),
        ),
    ]
