# Generated by Django 5.2.5 on 2025-10-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_alter_eventticketpayment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="churcheventticket",
            name="paid_status",
            field=models.CharField(
                choices=[
                    ("Fully Paid", "Fully Paid"),
                    ("Pending", "Pending"),
                    ("Partially Paid", "Partially Paid"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
