# Generated by Django 5.2.5 on 2025-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChurchPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                ("town", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                ("occupation", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
