# Generated by Django 5.2.5 on 2025-10-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcontribution",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="projectcontribution",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="projectpledge",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="projectpledge",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
