# Generated by Django 5.1.2 on 2025-05-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
