# Generated by Django 5.2.5 on 2025-08-28 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0008_alter_churchservice_service_day"),
        ("partners", "0001_initial"),
        ("projects", "0002_project_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcontribution",
            name="partner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partnerprojectcontributions",
                to="partners.churchpartner",
            ),
        ),
        migrations.AddField(
            model_name="projectpledge",
            name="full_redeemed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectpledge",
            name="partner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partnerprojectpledges",
                to="partners.churchpartner",
            ),
        ),
        migrations.AlterField(
            model_name="projectcontribution",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberprojectcontributions",
                to="membership.member",
            ),
        ),
        migrations.AlterField(
            model_name="projectpledge",
            name="member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="memberprojectpledges",
                to="membership.member",
            ),
        ),
    ]
