# Generated by Django 5.2.5 on 2025-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projectcontribution_partner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("Development", "Development"), ("Fundraiser", "Fundraiser")],
                default="Development",
                max_length=255,
            ),
        ),
    ]
