# Generated by Django 5.2.5 on 2025-08-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_project_description_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Ongoing", "Ongoing"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
