# Generated by Django 5.2.5 on 2025-08-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contribution_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
