# Generated by Django 5.2.5 on 2025-09-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("children", models.IntegerField(default=0)),
                ("adult", models.IntegerField(default=0)),
                ("month", models.CharField(max_length=255, null=True)),
                ("year", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("expense_name", models.CharField(max_length=255)),
                (
                    "amount_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("month", models.CharField(max_length=255, null=True)),
                ("year", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "general_fund",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "sunday_school",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "pastors_tithe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "presbyter_tithe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "easter",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "special_offering",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "kenya_kids",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "pastors_fund",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("month", models.CharField(max_length=255, null=True)),
                ("year", models.IntegerField(null=True)),
                (
                    "kagdom",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "district_missions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "resource_mobilisation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "church_support",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("meeting_date", models.DateField()),
                ("month", models.CharField(max_length=255, null=True)),
                ("year", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictMeetingAttendace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("present", models.BooleanField(default=False)),
                ("month", models.CharField(max_length=255, null=True)),
                ("year", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("month", models.CharField(max_length=255, null=True)),
                ("year", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "church",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="churchdistricts",
                        to="core.church",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
