# Generated by Django 5.2.5 on 2025-09-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0001_initial"),
        ("sections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("children", models.IntegerField(default=0)),
                ("adult", models.IntegerField(default=0)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districtattendance",
                        to="districts.district",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sections.section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "general_fund",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "sunday_school",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "pastors_tithe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "presbyter_tithe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "easter",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "special_offering",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districtfinances",
                        to="districts.district",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sections.section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
