# Generated by Django 5.2.5 on 2025-09-22 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("districts", "0001_initial"),
        ("sections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="supretendent",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="districtattendance",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districtattendance",
                to="districts.district",
            ),
        ),
        migrations.AddField(
            model_name="districtattendance",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sections.section",
            ),
        ),
        migrations.AddField(
            model_name="districtexpense",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districtexpenses",
                to="districts.district",
            ),
        ),
        migrations.AddField(
            model_name="districtfinance",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districtfinances",
                to="districts.district",
            ),
        ),
        migrations.AddField(
            model_name="districtfinance",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sections.section",
            ),
        ),
        migrations.AddField(
            model_name="districtmeeting",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="districts.district"
            ),
        ),
        migrations.AddField(
            model_name="districtmeetingattendace",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districtmeetingattendances",
                to="districts.districtmeeting",
            ),
        ),
        migrations.AddField(
            model_name="districtmeetingattendace",
            name="presbyter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="districtmeetingattendace",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sections.section"
            ),
        ),
        migrations.AddField(
            model_name="districtreport",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="districts.district",
            ),
        ),
        migrations.AddField(
            model_name="districtfinance",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="districts.districtreport",
            ),
        ),
        migrations.AddField(
            model_name="districtexpense",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="districts.districtreport",
            ),
        ),
        migrations.AddField(
            model_name="districtattendance",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="districts.districtreport",
            ),
        ),
    ]
