# Generated by Django 5.2.5 on 2025-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0002_districtattendance_districtfinance"),
    ]

    operations = [
        migrations.AddField(
            model_name="districtattendance",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="districtattendance",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="districtfinance",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="districtfinance",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
