# Generated by Django 5.2.5 on 2025-09-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0003_sectionreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionreport",
            name="church_welfare",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
