# Generated by Django 5.2.5 on 2025-09-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0004_districtreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="districtattendance",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="districts.districtreport",
            ),
        ),
        migrations.AddField(
            model_name="districtfinance",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="districts.districtreport",
            ),
        ),
    ]
