# Generated by Django 5.2.5 on 2025-09-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0004_sectionreport_church_welfare"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="districtmeetingattendace",
            name="presbyter",
        ),
        migrations.RemoveField(
            model_name="districtmeetingattendace",
            name="present",
        ),
        migrations.RemoveField(
            model_name="districtmeetingattendace",
            name="section",
        ),
        migrations.AddField(
            model_name="districtmeetingattendace",
            name="full_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="districtmeetingattendace",
            name="role",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="districtmeetingattendace",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
