# Generated by Django 5.2.5 on 2025-09-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0005_districtattendance_report_districtfinance_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="districtreport",
            name="adult",
        ),
        migrations.RemoveField(
            model_name="districtreport",
            name="children",
        ),
        migrations.RemoveField(
            model_name="districtreport",
            name="easter",
        ),
        migrations.RemoveField(
            model_name="districtreport",
            name="general_fund",
        ),
        migrations.RemoveField(
            model_name="districtreport",
            name="pastors_tithe",
        ),
        migrations.RemoveField(
            model_name="districtreport",
            name="presbyter_tithe",
        ),
        migrations.RemoveField(
            model_name="districtreport",
            name="special_offering",
        ),
        migrations.RemoveField(
            model_name="districtreport",
            name="sunday_school",
        ),
    ]
