# Generated by Django 5.2.5 on 2025-10-05 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0006_districtmeetingattendace_recorded_by"),
        ("membership", "0009_alter_branch_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionreport",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.branch",
            ),
        ),
    ]
