# Generated by Django 5.2.5 on 2025-09-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0006_remove_districtreport_adult_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="districtreport",
            name="section",
        ),
    ]
