# Generated by Django 5.2.5 on 2025-09-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0007_remove_districtreport_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="districtfinance",
            name="kenya_kids",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
