# Generated by Django 5.2.5 on 2025-10-18 11:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0008_remove_districtfinance_district_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="kagdistrictmonthlyreport",
            name="pastor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kagdistrictmonthlyreport",
            name="total_collected",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
    ]
