# Generated by Django 5.2.5 on 2025-09-11 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0008_districtfinance_kenya_kids"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("expense_name", models.CharField(max_length=255)),
                (
                    "amount_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("month", models.CharField(max_length=255, null=True)),
                ("year", models.IntegerField(null=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districtexpenses",
                        to="districts.district",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="districts.districtreport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
