# Generated by Django 5.2.5 on 2025-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0009_districtexpense"),
    ]

    operations = [
        migrations.AddField(
            model_name="districtfinance",
            name="pastors_fund",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
