# Generated by Django 5.2.5 on 2025-10-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0009_kagdistrictmonthlyreport_pastor_and_more"),
        ("users", "0009_alter_pastor_church"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kagdistrictmonthlyreport",
            name="pastor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.pastor",
            ),
        ),
    ]
