# Generated by Django 5.2.5 on 2025-10-21 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0010_alter_kagdistrictmonthlyreport_pastor"),
        ("sections", "0008_remove_sectionreport_adult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kagdistrictmonthlyreport",
            name="section_report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sections.sectionreport",
            ),
        ),
    ]
