# Generated by Django 5.2.5 on 2025-09-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0010_districtfinance_pastors_fund"),
    ]

    operations = [
        migrations.AddField(
            model_name="districtfinance",
            name="church_support",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="districtfinance",
            name="district_missions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="districtfinance",
            name="kagdom",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="districtfinance",
            name="resource_mobilisation",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
