# Generated by Django 5.2.5 on 2025-10-24 08:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0011_kagdistrictmonthlyreport_section_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="kagdistrictmonthlyreport",
            name="dsp_tithe",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
    ]
