from typing import Any, List, Dict
from apps.users.models import User
from apps.membership.models import Member, Branch, Department
from django.db import transaction

people = [
    {
        "first_name": "Jordon",
        "last_name": "Slide",
        "id_number": "156-41-0050",
        "department": 2,
        "branch": 5,
        "email": "jslide0@si.edu",
        "phone_number": "757-330-4478",
        "role": "Rev",
        "member_since": "2004-12-05",
        "gender": "Male",
        "address": "839 Scott Circle",
        "city": "Virginia Beach",
        "country": "Kenya",
    },
    {
        "first_name": "Palm",
        "last_name": "Winkworth",
        "id_number": "385-68-0417",
        "department": 1,
        "branch": 5,
        "email": "pwinkworth1@google.co.uk",
        "phone_number": "696-224-5070",
        "role": "Dr",
        "member_since": "2010-10-17",
        "gender": "Male",
        "address": "330 Lerdahl Place",
        "city": "Niuzhuang",
        "country": "Kenya",
    },
    {
        "first_name": "Penelopa",
        "last_name": "Acott",
        "id_number": "496-27-9729",
        "department": 3,
        "branch": 5,
        "email": "pacott2@joomla.org",
        "phone_number": "620-295-6829",
        "role": "Mr",
        "member_since": "2000-12-07",
        "gender": "Female",
        "address": "941 Ridge Oak Lane",
        "city": "Shikhazany",
        "country": "Kenya",
    },
    {
        "first_name": "Nikolaos",
        "last_name": "Fourman",
        "id_number": "410-25-8517",
        "department": 1,
        "branch": 5,
        "email": "nfourman3@sun.com",
        "phone_number": "572-716-2978",
        "role": "Mrs",
        "member_since": "2006-10-12",
        "gender": "Male",
        "address": "9728 Manufacturers Pass",
        "city": "Sindanghayu",
        "country": "Kenya",
    },
    {
        "first_name": "Pat",
        "last_name": "Noto",
        "id_number": "800-12-5506",
        "department": 3,
        "branch": 5,
        "email": "pnoto4@ted.com",
        "phone_number": "531-996-8661",
        "role": "Mrs",
        "member_since": "2006-10-20",
        "gender": "Male",
        "address": "4775 Scofield Parkway",
        "city": "Sanjiangkou",
        "country": "Kenya",
    },
    {
        "first_name": "Verile",
        "last_name": "Fairham",
        "id_number": "114-91-6381",
        "department": 1,
        "branch": 5,
        "email": "vfairham5@geocities.jp",
        "phone_number": "426-587-8400",
        "role": "Honorable",
        "member_since": "2002-03-01",
        "gender": "Female",
        "address": "27174 Montana Terrace",
        "city": "Zhanxu",
        "country": "Kenya",
    },
    {
        "first_name": "Giulio",
        "last_name": "Pleager",
        "id_number": "190-22-2216",
        "department": 2,
        "branch": 5,
        "email": "gpleager6@alexa.com",
        "phone_number": "600-503-9631",
        "role": "Honorable",
        "member_since": "2009-01-06",
        "gender": "Male",
        "address": "036 Maple Wood Plaza",
        "city": "Fécamp",
        "country": "Kenya",
    },
    {
        "first_name": "Libby",
        "last_name": "Amsberger",
        "id_number": "578-60-1545",
        "department": 1,
        "branch": 5,
        "email": "lamsberger7@answers.com",
        "phone_number": "133-754-4861",
        "role": "Mrs",
        "member_since": "2010-07-08",
        "gender": "Female",
        "address": "75 Morning Road",
        "city": "Chaem Luang",
        "country": "Kenya",
    },
    {
        "first_name": "Frederigo",
        "last_name": "Earsman",
        "id_number": "239-66-6077",
        "department": 1,
        "branch": 5,
        "email": "fearsman8@bbb.org",
        "phone_number": "374-390-6546",
        "role": "Ms",
        "member_since": "2018-11-07",
        "gender": "Male",
        "address": "5820 Anniversary Avenue",
        "city": "Cascavel",
        "country": "Kenya",
    },
    {
        "first_name": "Minetta",
        "last_name": "Thain",
        "id_number": "806-62-4423",
        "department": 2,
        "branch": 5,
        "email": "mthain9@redcross.org",
        "phone_number": "601-119-2861",
        "role": "Rev",
        "member_since": "2007-07-31",
        "gender": "Female",
        "address": "615 Dryden Avenue",
        "city": "Niaohe",
        "country": "Kenya",
    },
    {
        "first_name": "Guthry",
        "last_name": "Leemans",
        "id_number": "836-23-4708",
        "department": 3,
        "branch": 5,
        "email": "gleemansa@netvibes.com",
        "phone_number": "998-546-4353",
        "role": "Ms",
        "member_since": "2001-03-11",
        "gender": "Male",
        "address": "553 Bartelt Street",
        "city": "Santiago de Baney",
        "country": "Kenya",
    },
    {
        "first_name": "Joscelin",
        "last_name": "Boldry",
        "id_number": "724-36-3472",
        "department": 3,
        "branch": 5,
        "email": "jboldryb@vinaora.com",
        "phone_number": "927-374-7962",
        "role": "Mrs",
        "member_since": "2006-05-24",
        "gender": "Female",
        "address": "26 Union Street",
        "city": "Ushibuka",
        "country": "Kenya",
    },
    {
        "first_name": "Cchaddie",
        "last_name": "Casier",
        "id_number": "833-66-2845",
        "department": 3,
        "branch": 5,
        "email": "ccasierc@issuu.com",
        "phone_number": "656-310-1096",
        "role": "Mrs",
        "member_since": "2018-10-14",
        "gender": "Male",
        "address": "6 Dexter Park",
        "city": "Kaeng Khoi",
        "country": "Kenya",
    },
    {
        "first_name": "Tallulah",
        "last_name": "Chesnut",
        "id_number": "671-24-1586",
        "department": 1,
        "branch": 5,
        "email": "tchesnutd@smh.com.au",
        "phone_number": "425-940-9384",
        "role": "Dr",
        "member_since": "2007-04-21",
        "gender": "Female",
        "address": "13253 Northwestern Junction",
        "city": "Jiangkou",
        "country": "Kenya",
    },
    {
        "first_name": "Garv",
        "last_name": "Dewhurst",
        "id_number": "596-85-5198",
        "department": 2,
        "branch": 5,
        "email": "gdewhurste@wordpress.com",
        "phone_number": "795-903-6750",
        "role": "Ms",
        "member_since": "2013-06-10",
        "gender": "Male",
        "address": "2 Pearson Drive",
        "city": "Oebatu",
        "country": "Kenya",
    },
    {
        "first_name": "Demetra",
        "last_name": "Offield",
        "id_number": "340-32-0530",
        "department": 3,
        "branch": 5,
        "email": "doffieldf@msu.edu",
        "phone_number": "921-361-8764",
        "role": "Mrs",
        "member_since": "2006-03-20",
        "gender": "Female",
        "address": "61 Commercial Circle",
        "city": "Dapchi",
        "country": "Kenya",
    },
    {
        "first_name": "Rupert",
        "last_name": "Froment",
        "id_number": "484-02-3290",
        "department": 2,
        "branch": 5,
        "email": "rfromentg@pen.io",
        "phone_number": "159-241-6963",
        "role": "Ms",
        "member_since": "2007-02-02",
        "gender": "Male",
        "address": "3238 Pine View Trail",
        "city": "Enskede",
        "country": "Kenya",
    },
    {
        "first_name": "Celine",
        "last_name": "Cox",
        "id_number": "208-12-1652",
        "department": 3,
        "branch": 5,
        "email": "ccoxh@51.la",
        "phone_number": "713-285-8570",
        "role": "Mrs",
        "member_since": "2003-11-08",
        "gender": "Female",
        "address": "653 Milwaukee Avenue",
        "city": "Yaozhuang",
        "country": "Kenya",
    },
    {
        "first_name": "Saw",
        "last_name": "Whiffen",
        "id_number": "323-22-7432",
        "department": 1,
        "branch": 5,
        "email": "swhiffeni@exblog.jp",
        "phone_number": "712-711-7568",
        "role": "Rev",
        "member_since": "2002-10-02",
        "gender": "Male",
        "address": "84 Anthes Circle",
        "city": "Karangbaru",
        "country": "Kenya",
    },
    {
        "first_name": "Gib",
        "last_name": "Bernhardsson",
        "id_number": "523-56-4764",
        "department": 2,
        "branch": 5,
        "email": "gbernhardssonj@google.com",
        "phone_number": "953-247-8488",
        "role": "Mrs",
        "member_since": "2008-03-10",
        "gender": "Male",
        "address": "15 Onsgard Junction",
        "city": "Kangar",
        "country": "Kenya",
    },
    {
        "first_name": "Moll",
        "last_name": "Senyard",
        "id_number": "483-38-6862",
        "department": 1,
        "branch": 5,
        "email": "msenyardk@columbia.edu",
        "phone_number": "882-186-9683",
        "role": "Dr",
        "member_since": "2016-05-25",
        "gender": "Female",
        "address": "23 Blue Bill Park Circle",
        "city": "Marintoc",
        "country": "Kenya",
    },
    {
        "first_name": "Hillyer",
        "last_name": "Kinningley",
        "id_number": "532-92-6115",
        "department": 3,
        "branch": 5,
        "email": "hkinningleyl@wiley.com",
        "phone_number": "923-311-0168",
        "role": "Dr",
        "member_since": "2013-07-29",
        "gender": "Male",
        "address": "466 Clyde Gallagher Point",
        "city": "Jincheng",
        "country": "Kenya",
    },
    {
        "first_name": "Rozamond",
        "last_name": "Egginton",
        "id_number": "788-92-9686",
        "department": 1,
        "branch": 5,
        "email": "reggintonm@twitter.com",
        "phone_number": "713-873-1582",
        "role": "Mrs",
        "member_since": "2000-04-05",
        "gender": "Female",
        "address": "830 Tony Lane",
        "city": "Tongmuluo",
        "country": "Kenya",
    },
    {
        "first_name": "Read",
        "last_name": "Oneile",
        "id_number": "657-45-2013",
        "department": 2,
        "branch": 5,
        "email": "roneilen@mapquest.com",
        "phone_number": "201-634-5831",
        "role": "Rev",
        "member_since": "2009-12-14",
        "gender": "Male",
        "address": "5 Westport Crossing",
        "city": "Nogueira",
        "country": "Kenya",
    },
    {
        "first_name": "Paloma",
        "last_name": "Pinare",
        "id_number": "442-53-7489",
        "department": 2,
        "branch": 5,
        "email": "ppinareo@wikia.com",
        "phone_number": "701-811-9442",
        "role": "Rev",
        "member_since": "2009-01-24",
        "gender": "Female",
        "address": "3 Mallory Street",
        "city": "Petkovci",
        "country": "Kenya",
    },
    {
        "first_name": "Alfonse",
        "last_name": "Drever",
        "id_number": "353-77-1135",
        "department": 2,
        "branch": 5,
        "email": "adreverp@ebay.co.uk",
        "phone_number": "613-143-6369",
        "role": "Dr",
        "member_since": "2015-05-25",
        "gender": "Male",
        "address": "97822 Division Plaza",
        "city": "Tha Luang",
        "country": "Kenya",
    },
    {
        "first_name": "Marline",
        "last_name": "Pitsall",
        "id_number": "288-46-4037",
        "department": 1,
        "branch": 5,
        "email": "mpitsallq@canalblog.com",
        "phone_number": "904-310-1361",
        "role": "Dr",
        "member_since": "2002-12-06",
        "gender": "Female",
        "address": "6173 Harbort Road",
        "city": "Fenghuo",
        "country": "Kenya",
    },
    {
        "first_name": "Roseline",
        "last_name": "Marston",
        "id_number": "172-07-4665",
        "department": 2,
        "branch": 5,
        "email": "rmarstonr@jalbum.net",
        "phone_number": "722-201-6095",
        "role": "Mr",
        "member_since": "2003-09-19",
        "gender": "Female",
        "address": "6983 Columbus Parkway",
        "city": "Chernogorsk",
        "country": "Kenya",
    },
    {
        "first_name": "Balduin",
        "last_name": "McMakin",
        "id_number": "448-84-6441",
        "department": 3,
        "branch": 5,
        "email": "bmcmakins@webeden.co.uk",
        "phone_number": "118-506-6184",
        "role": "Mrs",
        "member_since": "2005-05-13",
        "gender": "Male",
        "address": "984 Sutherland Street",
        "city": "Kyzyl-Kyya",
        "country": "Kenya",
    },
    {
        "first_name": "Ranee",
        "last_name": "Baynes",
        "id_number": "800-60-8635",
        "department": 3,
        "branch": 5,
        "email": "rbaynest@wisc.edu",
        "phone_number": "979-652-2099",
        "role": "Mrs",
        "member_since": "2014-01-17",
        "gender": "Female",
        "address": "5 Carioca Street",
        "city": "Bryan",
        "country": "Kenya",
    },
    {
        "first_name": "Antonin",
        "last_name": "Foden",
        "id_number": "737-83-0712",
        "department": 3,
        "branch": 5,
        "email": "afodenu@baidu.com",
        "phone_number": "973-441-4655",
        "role": "Dr",
        "member_since": "2011-03-14",
        "gender": "Male",
        "address": "4 Monterey Pass",
        "city": "Rio de Moinhos",
        "country": "Kenya",
    },
    {
        "first_name": "Adan",
        "last_name": "Aspenlon",
        "id_number": "209-01-1597",
        "department": 1,
        "branch": 5,
        "email": "aaspenlonv@whitehouse.gov",
        "phone_number": "723-607-7518",
        "role": "Mrs",
        "member_since": "2010-01-15",
        "gender": "Male",
        "address": "986 Packers Center",
        "city": "Ukata",
        "country": "Kenya",
    },
    {
        "first_name": "Brinna",
        "last_name": "Delos",
        "id_number": "621-73-2456",
        "department": 1,
        "branch": 5,
        "email": "bdelosw@joomla.org",
        "phone_number": "837-521-8594",
        "role": "Dr",
        "member_since": "2018-08-04",
        "gender": "Female",
        "address": "08 Bowman Parkway",
        "city": "Zhengyangshan",
        "country": "Kenya",
    },
    {
        "first_name": "Ira",
        "last_name": "Jimeno",
        "id_number": "816-90-4466",
        "department": 1,
        "branch": 5,
        "email": "ijimenox@eepurl.com",
        "phone_number": "634-207-5937",
        "role": "Mr",
        "member_since": "2016-06-16",
        "gender": "Female",
        "address": "9846 Bellgrove Parkway",
        "city": "Caucete",
        "country": "Kenya",
    },
    {
        "first_name": "Halie",
        "last_name": "Hacun",
        "id_number": "273-95-9313",
        "department": 2,
        "branch": 5,
        "email": "hhacuny@europa.eu",
        "phone_number": "136-615-1210",
        "role": "Mrs",
        "member_since": "2006-11-24",
        "gender": "Female",
        "address": "07626 Farragut Lane",
        "city": "Farasān",
        "country": "Kenya",
    },
    {
        "first_name": "Sigismondo",
        "last_name": "Breheny",
        "id_number": "745-83-7054",
        "department": 1,
        "branch": 5,
        "email": "sbrehenyz@google.cn",
        "phone_number": "927-506-0388",
        "role": "Mr",
        "member_since": "2016-06-26",
        "gender": "Male",
        "address": "03007 Westport Alley",
        "city": "Kezilei",
        "country": "Kenya",
    },
    {
        "first_name": "Danell",
        "last_name": "Witherden",
        "id_number": "258-39-5932",
        "department": 2,
        "branch": 5,
        "email": "dwitherden10@prlog.org",
        "phone_number": "756-437-0957",
        "role": "Dr",
        "member_since": "2014-07-15",
        "gender": "Female",
        "address": "08 Glendale Junction",
        "city": "Delft",
        "country": "Kenya",
    },
    {
        "first_name": "Gerry",
        "last_name": "Narbett",
        "id_number": "796-29-1393",
        "department": 1,
        "branch": 5,
        "email": "gnarbett11@photobucket.com",
        "phone_number": "178-612-5732",
        "role": "Ms",
        "member_since": "2018-12-26",
        "gender": "Male",
        "address": "877 Memorial Park",
        "city": "Latacunga",
        "country": "Kenya",
    },
    {
        "first_name": "Lindsey",
        "last_name": "Coltherd",
        "id_number": "564-45-1309",
        "department": 3,
        "branch": 5,
        "email": "lcoltherd12@ucla.edu",
        "phone_number": "865-718-1167",
        "role": "Honorable",
        "member_since": "2007-11-12",
        "gender": "Female",
        "address": "74 Corry Crossing",
        "city": "La Cruz",
        "country": "Kenya",
    },
    {
        "first_name": "Guthrey",
        "last_name": "Rock",
        "id_number": "786-72-8643",
        "department": 2,
        "branch": 5,
        "email": "grock13@examiner.com",
        "phone_number": "520-456-7115",
        "role": "Rev",
        "member_since": "2003-03-08",
        "gender": "Male",
        "address": "7 Forest Dale Alley",
        "city": "Morazán",
        "country": "Kenya",
    },
    {
        "first_name": "Hatti",
        "last_name": "Ponnsett",
        "id_number": "371-19-3906",
        "department": 3,
        "branch": 5,
        "email": "hponnsett14@etsy.com",
        "phone_number": "385-426-6214",
        "role": "Ms",
        "member_since": "2017-06-29",
        "gender": "Female",
        "address": "08 Dahle Point",
        "city": "São João de Meriti",
        "country": "Kenya",
    },
    {
        "first_name": "Broddie",
        "last_name": "Upshall",
        "id_number": "615-17-0878",
        "department": 2,
        "branch": 5,
        "email": "bupshall15@google.co.jp",
        "phone_number": "509-653-7030",
        "role": "Mr",
        "member_since": "2016-06-20",
        "gender": "Male",
        "address": "791 Forest Dale Hill",
        "city": "Ketovo",
        "country": "Kenya",
    },
    {
        "first_name": "Moises",
        "last_name": "Patty",
        "id_number": "832-41-8300",
        "department": 3,
        "branch": 5,
        "email": "mpatty16@google.fr",
        "phone_number": "968-297-5033",
        "role": "Dr",
        "member_since": "2013-05-19",
        "gender": "Male",
        "address": "346 Morningstar Plaza",
        "city": "Sanqishi",
        "country": "Kenya",
    },
    {
        "first_name": "Virgie",
        "last_name": "Himsworth",
        "id_number": "135-02-2485",
        "department": 3,
        "branch": 5,
        "email": "vhimsworth17@newyorker.com",
        "phone_number": "525-207-2164",
        "role": "Honorable",
        "member_since": "2010-05-16",
        "gender": "Male",
        "address": "6591 Eggendart Street",
        "city": "Galūgāh",
        "country": "Kenya",
    },
    {
        "first_name": "Monika",
        "last_name": "Simka",
        "id_number": "616-53-6350",
        "department": 3,
        "branch": 5,
        "email": "msimka18@tinypic.com",
        "phone_number": "672-681-0087",
        "role": "Mrs",
        "member_since": "2007-10-27",
        "gender": "Female",
        "address": "7 Goodland Terrace",
        "city": "Podbrdo",
        "country": "Kenya",
    },
    {
        "first_name": "Kiele",
        "last_name": "Jeannaud",
        "id_number": "158-65-5418",
        "department": 3,
        "branch": 5,
        "email": "kjeannaud19@moonfruit.com",
        "phone_number": "990-263-8449",
        "role": "Ms",
        "member_since": "2013-04-08",
        "gender": "Female",
        "address": "6 Grover Place",
        "city": "Naj‘ Ḩammādī",
        "country": "Kenya",
    },
]


class LoadMembers:
    def __init__(self):
        pass

    @transaction.atomic
    def load_members(self) -> None:
        for x in people:
            first_name = x.get("first_name")
            last_name = x.get("last_name")
            id_number = x.get("id_number")
            department = x.get("department")
            branch = x.get("branch")
            email = x.get("email")
            phone_number = x.get("phone_number")
            role = x.get("role")
            member_since = x.get("member_since")
            gender = x.get("gender")
            address = x.get("address")
            city = x.get("city")
            country = x.get("country")

            user = User.objects.filter(email=email).first()
            if user:
                print(f"User with email {email} already exists. Skipping...")
            else:
                user = User.objects.create(
                    first_name=first_name,
                    last_name=last_name,
                    id_number=id_number,
                    email=email,
                    role=role,
                    phone_number=phone_number,
                    username=email,
                    gender=gender,
                    address=address,
                    city=city,
                    country=country,
                    password="1234",
                )

                Member.objects.create(
                    user=user,
                    member_since=member_since,
                    position=role,
                    department_id=department,
                    branch_id=branch,
                    status="Active",
                )
                print("Members loaded successfully.")
