# Generated by Django 5.2.5 on 2025-09-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500, null=True)),
                ("town", models.CharField(max_length=255)),
                ("country", models.CharField(default="Kenya", max_length=255)),
                ("phone", models.CharField(max_length=20, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("website", models.URLField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
