# Generated by Django 5.2.5 on 2025-09-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="church_type",
            field=models.CharField(
                choices=[
                    ("Single Church", "Single Church"),
                    ("Multi Branch Church", "Multi Branch Church"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="denomination",
            field=models.CharField(
                choices=[
                    ("Anglican", "Anglican"),
                    ("Catholic", "Catholic"),
                    ("Protestant", "Protestant"),
                    ("Pentecostal", "Pentecostal"),
                    ("Evangelical", "Evangelical"),
                    ("Seventh-day Adventist", "Seventh-day Adventist"),
                    ("Jehovah's Witnesses", "Jehovah's Witnesses"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="church",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="church_logos/"),
        ),
    ]
