# Generated by Django 5.2.5 on 2025-10-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_church_church_type_church_denomination_church_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=255)),
                ("currency_code", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
