# Generated by Django 5.2.5 on 2025-10-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="church",
            name="country",
        ),
    ]
