# Generated by Django 5.2.5 on 2025-10-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_churchofferingtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="church",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.country",
            ),
        ),
    ]
