# Generated by Django 5.2.5 on 2025-09-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendances", "0001_initial"),
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberoffering",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendances.churchservice",
            ),
        ),
        migrations.AlterField(
            model_name="offering",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendances.churchservice",
            ),
        ),
    ]
