# Generated by Django 5.2.5 on 2025-09-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_memberoffering_service_alter_offering_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchdonation",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="churchdonation",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="churchexpense",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="churchexpense",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="departmentsaving",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="departmentsaving",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="memberdepartmentsaving",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="memberdepartmentsaving",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="memberoffering",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="memberoffering",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="membertithing",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="membertithing",
            name="year",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="offering",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="offering",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
