# Generated by Django 5.2.5 on 2025-09-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_churchdonation_month_churchdonation_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchledger",
            name="transaction_date",
            field=models.DateField(null=True),
        ),
    ]
