# Generated by Django 5.2.5 on 2025-10-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_churchrole"),
        ("payments", "0005_churchledger_transaction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchdonation",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.church",
            ),
        ),
        migrations.AddField(
            model_name="churchexpense",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.church",
            ),
        ),
        migrations.AddField(
            model_name="churchledger",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.church",
            ),
        ),
        migrations.AddField(
            model_name="departmentsaving",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.church",
            ),
        ),
        migrations.AddField(
            model_name="memberdepartmentsaving",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.church",
            ),
        ),
        migrations.AddField(
            model_name="memberoffering",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.church",
            ),
        ),
        migrations.AddField(
            model_name="membertithing",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.church",
            ),
        ),
        migrations.AddField(
            model_name="offering",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.church",
            ),
        ),
        migrations.AddField(
            model_name="offering",
            name="offering_type",
            field=models.CharField(default="General", max_length=255, null=True),
        ),
    ]
