# Generated by Django 5.2.5 on 2025-08-28 15:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0008_alter_churchservice_service_day"),
        ("partners", "0001_initial"),
        ("payments", "0005_memberdepartmentsaving"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("donation_date", models.DateField()),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partnerdonations",
                        to="membership.member",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberdonations",
                        to="partners.churchpartner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
