# Generated by Django 5.2.5 on 2025-10-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_churchdonation_church_churchexpense_church_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchledger",
            name="txn_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
