# Generated by Django 5.2.5 on 2025-09-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_churchledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchledger",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="churchledger",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
