# Generated by Django 5.2.5 on 2025-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_churchledger_txn_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="membertithing",
            name="tithe_channel",
            field=models.CharField(default="Cash", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offering",
            name="offering_channel",
            field=models.CharField(default="Cash", max_length=255, null=True),
        ),
    ]
