# Generated by Django 5.2.5 on 2025-09-06 09:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_churchledger_month_churchledger_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchledger",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=1000
            ),
        ),
    ]
