# Generated by Django 5.2.5 on 2025-10-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_membertithing_tithe_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offering",
            name="offering_channel",
        ),
        migrations.RemoveField(
            model_name="offering",
            name="offering_type",
        ),
    ]
