# Generated by Django 5.2.5 on 2025-10-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_churchofferingchannel"),
        ("payments", "0009_remove_offering_offering_channel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membertithing",
            name="tithe_channel",
        ),
        migrations.AddField(
            model_name="offering",
            name="offering_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.churchofferingchannel",
            ),
        ),
        migrations.AddField(
            model_name="offering",
            name="offering_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.churchofferingtype",
            ),
        ),
    ]
