# Generated by Django 5.2.5 on 2025-09-06 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_churchledger_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="churchdonation",
            name="member",
        ),
        migrations.RemoveField(
            model_name="churchdonation",
            name="partner",
        ),
        migrations.AddField(
            model_name="churchdonation",
            name="captured_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="churchdonation",
            name="donor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="churchdonation",
            name="purpose",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="churchdonation",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
