# Generated by Django 5.2.5 on 2025-10-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_churchofferingchannel"),
        ("payments", "0010_remove_membertithing_tithe_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membertithing",
            name="tithe_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.churchofferingchannel",
            ),
        ),
    ]
