# Generated by Django 5.1.2 on 2025-05-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
