# Generated by Django 5.2.5 on 2025-09-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendances", "0001_initial"),
        ("users", "0002_user_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="church_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendances.churchservice",
            ),
        ),
    ]
