# Generated by Django 5.2.5 on 2025-10-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0009_alter_branch_section"),
        ("users", "0003_alter_visitor_church_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pastor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "church",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="churchpastor",
                        to="membership.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
