# Generated by Django 5.1.2 on 2025-08-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0008_alter_churchservice_service_day"),
        ("users", "0003_visitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.branch",
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="church_service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.churchservice",
            ),
        ),
    ]
