# Generated by Django 5.2.5 on 2025-09-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_church"),
        ("users", "0004_visitor_branch_visitor_church_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.church",
            ),
        ),
    ]
