# Generated by Django 5.2.5 on 2025-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="times_attended",
            field=models.IntegerField(default=1),
        ),
    ]
