# Generated by Django 5.2.5 on 2025-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_visitor_times_attended"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="converted",
            field=models.BooleanField(default=False),
        ),
    ]
