# Generated by Django 5.2.5 on 2025-09-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Church Member", "Church Member"),
                    ("Pastor", "Pastor"),
                    ("Men Department Leader", "Men Department Leader"),
                    ("Women Department Leader", "Women Department Leader"),
                    ("Teens Department Leader", "Teens Department Leader"),
                    ("Church Secretary", "Church Secretary"),
                    ("Church Treasurer", "Church Treasurer"),
                    ("District Supritendant", "District Supritendant"),
                    ("Presbyter", "Presbyter"),
                ],
                default="Church Member",
                max_length=255,
            ),
        ),
    ]
