# Generated by Django 5.2.5 on 2025-10-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_visitor_converted"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastor",
            name="pastor_role",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
