# Generated by Django 5.2.5 on 2025-10-13 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0011_remove_membergroup_chairperson_and_more"),
        ("users", "0008_pastor_pastor_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pastor",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="churchpastors",
                to="membership.branch",
            ),
        ),
    ]
