# Generated by Django 5.2.5 on 2025-10-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_churchrole"),
        ("users", "0009_alter_pastor_church"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userchurch",
                to="core.church",
            ),
        ),
    ]
