# Generated by Django 5.2.5 on 2025-10-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneyaccount",
            name="is_expense_account",
            field=models.BooleanField(default=False),
        ),
    ]
