# Generated by Django 5.2.5 on 2025-10-13 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_moneyaccount_is_expense_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moneyaccounttransaction",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="moneyaccounttransaction",
            name="source",
        ),
        migrations.AddField(
            model_name="moneyaccounttransaction",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactingaccounts",
                to="finances.moneyaccount",
            ),
        ),
        migrations.AddField(
            model_name="moneyaccounttransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Credit", "Credit"), ("Debit", "Debit")],
                max_length=255,
                null=True,
            ),
        ),
    ]
