# Generated by Django 5.2.5 on 2025-10-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0003_remove_moneyaccounttransaction_destination_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moneyaccounttransaction",
            name="account",
        ),
        migrations.AddField(
            model_name="moneyaccounttransaction",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destinationaccounts",
                to="finances.moneyaccount",
            ),
        ),
        migrations.AddField(
            model_name="moneyaccounttransaction",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sourceaccounts",
                to="finances.moneyaccount",
            ),
        ),
    ]
