from apps.core.constants import get_month_name, get_month_number, format_date
from apps.payments.models import ChurchDonation, ChurchLedger
from apps.users.models import User

user = User.objects.filter(username="admin").first()
records = [
    {
        "donor": "Bernarr Patemore",
        "purpose": "Projects Support",
        "amount": 460622,
        "donation_date": "2023-01-24",
    },
    {
        "donor": "Earl Coppock.",
        "purpose": "Church Support",
        "amount": 215676,
        "donation_date": "2025-01-26",
    },
    {
        "donor": "Sheffy Rove",
        "purpose": "Projects Support",
        "amount": 801952,
        "donation_date": "2021-09-28",
    },
    {
        "donor": "Katy Trask",
        "purpose": "Projects Support",
        "amount": 503046,
        "donation_date": "2023-01-15",
    },
    {
        "donor": "Kristel Skamal",
        "purpose": "Church Support",
        "amount": 456162,
        "donation_date": "2024-11-17",
    },
    {
        "donor": "Thomasine Dickings",
        "purpose": "Church Support",
        "amount": 646042,
        "donation_date": "2020-11-23",
    },
    {
        "donor": "Nap Doyle",
        "purpose": "Church Support",
        "amount": 393595,
        "donation_date": "2024-04-02",
    },
    {
        "donor": "Josee Biasioli",
        "purpose": "Projects Support",
        "amount": 736192,
        "donation_date": "2024-09-12",
    },
    {
        "donor": "Kellie Askwith",
        "purpose": "Church Support",
        "amount": 820128,
        "donation_date": "2022-03-02",
    },
    {
        "donor": "Tanitansy Flowerden",
        "purpose": "Church Support",
        "amount": 157880,
        "donation_date": "2024-09-18",
    },
    {
        "donor": "Jillane Neal",
        "purpose": "Projects Support",
        "amount": 506523,
        "donation_date": "2022-12-10",
    },
    {
        "donor": "Cordy Flood",
        "purpose": "Projects Support",
        "amount": 770398,
        "donation_date": "2020-11-03",
    },
    {
        "donor": "Karlotte Yeardsley",
        "purpose": "Projects Support",
        "amount": 852584,
        "donation_date": "2021-09-04",
    },
    {
        "donor": "Joachim Croot",
        "purpose": "Church Support",
        "amount": 951576,
        "donation_date": "2022-04-01",
    },
    {
        "donor": "Saraann Spatig",
        "purpose": "Church Support",
        "amount": 292010,
        "donation_date": "2024-01-17",
    },
    {
        "donor": "Dulcia Stokoe",
        "purpose": "Church Support",
        "amount": 792475,
        "donation_date": "2023-08-25",
    },
    {
        "donor": "Melodie Neville",
        "purpose": "Projects Support",
        "amount": 563889,
        "donation_date": "2024-12-02",
    },
    {
        "donor": "Forster Swinyard",
        "purpose": "Projects Support",
        "amount": 772218,
        "donation_date": "2022-11-06",
    },
    {
        "donor": "Micheal Barroux",
        "purpose": "Projects Support",
        "amount": 921546,
        "donation_date": "2025-02-13",
    },
    {
        "donor": "Wilmer Duker",
        "purpose": "Projects Support",
        "amount": 19722,
        "donation_date": "2024-11-14",
    },
    {
        "donor": "Merci Putson",
        "purpose": "Church Support",
        "amount": 848203,
        "donation_date": "2021-12-30",
    },
    {
        "donor": "Hyacinthia Nerheny",
        "purpose": "Projects Support",
        "amount": 105096,
        "donation_date": "2025-01-04",
    },
    {
        "donor": "Mavis Bittlestone",
        "purpose": "Projects Support",
        "amount": 245607,
        "donation_date": "2021-11-05",
    },
    {
        "donor": "Chelsae Littrick",
        "purpose": "Projects Support",
        "amount": 339439,
        "donation_date": "2021-04-30",
    },
    {
        "donor": "Dani Overill",
        "purpose": "Projects Support",
        "amount": 773322,
        "donation_date": "2023-04-17",
    },
    {
        "donor": "Roosevelt Lusher",
        "purpose": "Church Support",
        "amount": 508953,
        "donation_date": "2020-09-28",
    },
    {
        "donor": "Trista Reeday",
        "purpose": "Projects Support",
        "amount": 739504,
        "donation_date": "2024-10-01",
    },
    {
        "donor": "Hildy Yewdale",
        "purpose": "Church Support",
        "amount": 165904,
        "donation_date": "2021-05-19",
    },
    {
        "donor": "Ardene Tweedie",
        "purpose": "Projects Support",
        "amount": 732061,
        "donation_date": "2023-06-03",
    },
    {
        "donor": "Goran Calcut",
        "purpose": "Projects Support",
        "amount": 397569,
        "donation_date": "2021-12-14",
    },
    {
        "donor": "Rosemarie O'Lennane",
        "purpose": "Projects Support",
        "amount": 64984,
        "donation_date": "2022-01-11",
    },
    {
        "donor": "Jessee Posselt",
        "purpose": "Projects Support",
        "amount": 427291,
        "donation_date": "2020-08-25",
    },
    {
        "donor": "Earle Dundridge",
        "purpose": "Projects Support",
        "amount": 744025,
        "donation_date": "2025-06-04",
    },
    {
        "donor": "Delcine Kimmings",
        "purpose": "Projects Support",
        "amount": 595110,
        "donation_date": "2021-11-02",
    },
    {
        "donor": "Mordecai Chessum",
        "purpose": "Projects Support",
        "amount": 339945,
        "donation_date": "2025-01-10",
    },
    {
        "donor": "Willy Martinolli",
        "purpose": "Projects Support",
        "amount": 436487,
        "donation_date": "2024-11-05",
    },
    {
        "donor": "Bernette Henfre",
        "purpose": "Projects Support",
        "amount": 86864,
        "donation_date": "2020-06-20",
    },
    {
        "donor": "Joanie Zmitruk",
        "purpose": "Church Support",
        "amount": 407090,
        "donation_date": "2021-01-08",
    },
    {
        "donor": "Filberto Tiner",
        "purpose": "Church Support",
        "amount": 972538,
        "donation_date": "2024-09-02",
    },
    {
        "donor": "Michel Redfern",
        "purpose": "Church Support",
        "amount": 270097,
        "donation_date": "2020-08-14",
    },
    {
        "donor": "Terrel McKelloch",
        "purpose": "Projects Support",
        "amount": 262509,
        "donation_date": "2022-05-27",
    },
    {
        "donor": "Margi Bargery",
        "purpose": "Church Support",
        "amount": 725441,
        "donation_date": "2025-01-05",
    },
    {
        "donor": "Sydney Bravington",
        "purpose": "Projects Support",
        "amount": 439600,
        "donation_date": "2025-04-05",
    },
    {
        "donor": "Jere Breming",
        "purpose": "Church Support",
        "amount": 583680,
        "donation_date": "2024-05-08",
    },
    {
        "donor": "Leigha Goldthorp",
        "purpose": "Projects Support",
        "amount": 814963,
        "donation_date": "2025-05-11",
    },
    {
        "donor": "Alyssa Kynnd",
        "purpose": "Church Support",
        "amount": 401823,
        "donation_date": "2022-08-08",
    },
    {
        "donor": "Pierette Karpushkin",
        "purpose": "Church Support",
        "amount": 479430,
        "donation_date": "2022-06-28",
    },
    {
        "donor": "Gladys Iliff",
        "purpose": "Projects Support",
        "amount": 104116,
        "donation_date": "2023-04-11",
    },
    {
        "donor": "Thor Wenden",
        "purpose": "Church Support",
        "amount": 254188,
        "donation_date": "2021-09-07",
    },
    {
        "donor": "Stefan Bellefonte",
        "purpose": "Projects Support",
        "amount": 915762,
        "donation_date": "2021-03-31",
    },
    {
        "donor": "Maura Causbey",
        "purpose": "Projects Support",
        "amount": 94888,
        "donation_date": "2022-02-02",
    },
    {
        "donor": "Tyler Stackbridge",
        "purpose": "Projects Support",
        "amount": 469707,
        "donation_date": "2022-07-06",
    },
    {
        "donor": "Gayler Philpault",
        "purpose": "Church Support",
        "amount": 796492,
        "donation_date": "2020-10-21",
    },
    {
        "donor": "Thane Sleite",
        "purpose": "Church Support",
        "amount": 130699,
        "donation_date": "2024-02-08",
    },
    {
        "donor": "Heather Guiot",
        "purpose": "Church Support",
        "amount": 150461,
        "donation_date": "2022-01-24",
    },
    {
        "donor": "Eolande Heeps",
        "purpose": "Church Support",
        "amount": 36553,
        "donation_date": "2022-01-12",
    },
    {
        "donor": "Queenie Wrathall",
        "purpose": "Projects Support",
        "amount": 475197,
        "donation_date": "2021-07-02",
    },
    {
        "donor": "Shae Spittle",
        "purpose": "Projects Support",
        "amount": 440324,
        "donation_date": "2022-03-01",
    },
    {
        "donor": "Walton Beeck",
        "purpose": "Church Support",
        "amount": 941722,
        "donation_date": "2023-08-28",
    },
    {
        "donor": "Fabien Walne",
        "purpose": "Projects Support",
        "amount": 908558,
        "donation_date": "2022-06-15",
    },
    {
        "donor": "Oberon Pinkstone",
        "purpose": "Projects Support",
        "amount": 563165,
        "donation_date": "2024-01-02",
    },
    {
        "donor": "Colas Bax",
        "purpose": "Projects Support",
        "amount": 212090,
        "donation_date": "2023-04-21",
    },
    {
        "donor": "Carlotta Skegg",
        "purpose": "Church Support",
        "amount": 413151,
        "donation_date": "2020-08-30",
    },
    {
        "donor": "Gnni Conybear",
        "purpose": "Church Support",
        "amount": 129258,
        "donation_date": "2021-12-25",
    },
    {
        "donor": "Forster Pascoe",
        "purpose": "Church Support",
        "amount": 527798,
        "donation_date": "2025-02-20",
    },
    {
        "donor": "Kathlin Lesser",
        "purpose": "Church Support",
        "amount": 110975,
        "donation_date": "2022-01-14",
    },
    {
        "donor": "Tyrus Berthouloume",
        "purpose": "Projects Support",
        "amount": 989735,
        "donation_date": "2021-03-14",
    },
    {
        "donor": "Briant Jagoe",
        "purpose": "Church Support",
        "amount": 190958,
        "donation_date": "2022-06-25",
    },
    {
        "donor": "Maia Rippingale",
        "purpose": "Projects Support",
        "amount": 728020,
        "donation_date": "2023-11-07",
    },
    {
        "donor": "Lavinie Cawdron",
        "purpose": "Projects Support",
        "amount": 733331,
        "donation_date": "2022-06-16",
    },
    {
        "donor": "Hetti O'Donohue",
        "purpose": "Projects Support",
        "amount": 310666,
        "donation_date": "2022-05-29",
    },
    {
        "donor": "Godfree Monahan",
        "purpose": "Projects Support",
        "amount": 555825,
        "donation_date": "2024-04-20",
    },
    {
        "donor": "Philomena Luscott",
        "purpose": "Projects Support",
        "amount": 61539,
        "donation_date": "2023-02-06",
    },
    {
        "donor": "Caspar Dunthorn",
        "purpose": "Projects Support",
        "amount": 68903,
        "donation_date": "2020-10-25",
    },
    {
        "donor": "Cherise Pauling",
        "purpose": "Church Support",
        "amount": 597890,
        "donation_date": "2020-05-14",
    },
    {
        "donor": "Rachele Yeats",
        "purpose": "Church Support",
        "amount": 285719,
        "donation_date": "2025-06-30",
    },
    {
        "donor": "Eloisa Steggles",
        "purpose": "Church Support",
        "amount": 244162,
        "donation_date": "2022-11-15",
    },
    {
        "donor": "Carling Gooderick",
        "purpose": "Church Support",
        "amount": 923972,
        "donation_date": "2023-11-27",
    },
    {
        "donor": "Filmer Mayhow",
        "purpose": "Projects Support",
        "amount": 667763,
        "donation_date": "2021-10-18",
    },
    {
        "donor": "Mel Goodyear",
        "purpose": "Projects Support",
        "amount": 90724,
        "donation_date": "2024-05-20",
    },
    {
        "donor": "Thibaut Gatenby",
        "purpose": "Church Support",
        "amount": 247336,
        "donation_date": "2024-11-17",
    },
    {
        "donor": "Eolanda Scala",
        "purpose": "Projects Support",
        "amount": 449675,
        "donation_date": "2022-01-21",
    },
    {
        "donor": "Diego Zarfat",
        "purpose": "Projects Support",
        "amount": 788554,
        "donation_date": "2021-11-08",
    },
    {
        "donor": "Prisca Niset",
        "purpose": "Projects Support",
        "amount": 250994,
        "donation_date": "2020-07-26",
    },
    {
        "donor": "Twyla Watchorn",
        "purpose": "Projects Support",
        "amount": 200311,
        "donation_date": "2024-11-03",
    },
    {
        "donor": "Gabriello Elfes",
        "purpose": "Church Support",
        "amount": 363529,
        "donation_date": "2020-01-31",
    },
    {
        "donor": "Shea Regitz",
        "purpose": "Projects Support",
        "amount": 305639,
        "donation_date": "2023-06-29",
    },
    {
        "donor": "Eliot Petch",
        "purpose": "Church Support",
        "amount": 575244,
        "donation_date": "2020-03-19",
    },
    {
        "donor": "Demott Manson",
        "purpose": "Projects Support",
        "amount": 573283,
        "donation_date": "2023-04-14",
    },
    {
        "donor": "Chris Tinson",
        "purpose": "Church Support",
        "amount": 364004,
        "donation_date": "2025-07-23",
    },
    {
        "donor": "Nada Endecott",
        "purpose": "Church Support",
        "amount": 790284,
        "donation_date": "2021-07-23",
    },
    {
        "donor": "Karil Keough",
        "purpose": "Projects Support",
        "amount": 870717,
        "donation_date": "2024-09-16",
    },
    {
        "donor": "Melva Quick",
        "purpose": "Church Support",
        "amount": 615025,
        "donation_date": "2024-11-18",
    },
    {
        "donor": "Kali Janosevic",
        "purpose": "Projects Support",
        "amount": 608167,
        "donation_date": "2021-02-10",
    },
    {
        "donor": "Gerardo Gordon-Giles",
        "purpose": "Church Support",
        "amount": 296267,
        "donation_date": "2023-11-19",
    },
    {
        "donor": "Cozmo Sylvaine",
        "purpose": "Projects Support",
        "amount": 525069,
        "donation_date": "2025-04-24",
    },
    {
        "donor": "Reggy Rosel",
        "purpose": "Projects Support",
        "amount": 655837,
        "donation_date": "2022-05-05",
    },
    {
        "donor": "Tamra Raoux",
        "purpose": "Projects Support",
        "amount": 55219,
        "donation_date": "2021-06-07",
    },
    {
        "donor": "Chris Worden",
        "purpose": "Projects Support",
        "amount": 853890,
        "donation_date": "2020-10-25",
    },
    {
        "donor": "Kippy Abella",
        "purpose": "Church Support",
        "amount": 981826,
        "donation_date": "2021-08-15",
    },
    {
        "donor": "Eleen Sharpling",
        "purpose": "Projects Support",
        "amount": 335266,
        "donation_date": "2020-11-13",
    },
    {
        "donor": "Ara Avard",
        "purpose": "Projects Support",
        "amount": 116547,
        "donation_date": "2020-10-16",
    },
    {
        "donor": "Rodd Stickel",
        "purpose": "Projects Support",
        "amount": 606025,
        "donation_date": "2023-04-19",
    },
    {
        "donor": "Jerrie Girardoni",
        "purpose": "Projects Support",
        "amount": 378264,
        "donation_date": "2025-05-10",
    },
    {
        "donor": "Ryon McGregor",
        "purpose": "Projects Support",
        "amount": 224565,
        "donation_date": "2020-07-04",
    },
    {
        "donor": "Emanuel Kerans",
        "purpose": "Church Support",
        "amount": 28690,
        "donation_date": "2022-02-04",
    },
    {
        "donor": "Jo ann Blackbrough",
        "purpose": "Church Support",
        "amount": 718335,
        "donation_date": "2020-12-23",
    },
    {
        "donor": "Adelheid McIlrath",
        "purpose": "Church Support",
        "amount": 432100,
        "donation_date": "2021-01-01",
    },
    {
        "donor": "Glyn Ysson",
        "purpose": "Projects Support",
        "amount": 303432,
        "donation_date": "2024-12-17",
    },
    {
        "donor": "Giana Kuhlen",
        "purpose": "Church Support",
        "amount": 258546,
        "donation_date": "2020-09-15",
    },
    {
        "donor": "Lari Swane",
        "purpose": "Projects Support",
        "amount": 117673,
        "donation_date": "2021-01-06",
    },
    {
        "donor": "Camilla Strute",
        "purpose": "Projects Support",
        "amount": 798502,
        "donation_date": "2022-05-20",
    },
    {
        "donor": "Clayton Doudney",
        "purpose": "Church Support",
        "amount": 415763,
        "donation_date": "2020-06-15",
    },
    {
        "donor": "Tiffany Purcell",
        "purpose": "Projects Support",
        "amount": 572462,
        "donation_date": "2020-10-07",
    },
    {
        "donor": "Steffi Stenet",
        "purpose": "Church Support",
        "amount": 838458,
        "donation_date": "2021-11-02",
    },
    {
        "donor": "Lori Logan",
        "purpose": "Church Support",
        "amount": 117354,
        "donation_date": "2022-02-09",
    },
    {
        "donor": "Dyann Blakiston",
        "purpose": "Projects Support",
        "amount": 905214,
        "donation_date": "2022-02-26",
    },
    {
        "donor": "Rhodia Largen",
        "purpose": "Church Support",
        "amount": 443689,
        "donation_date": "2023-09-25",
    },
    {
        "donor": "Tybalt Lanchbury",
        "purpose": "Church Support",
        "amount": 60793,
        "donation_date": "2023-02-03",
    },
    {
        "donor": "Teodoor Pechan",
        "purpose": "Church Support",
        "amount": 106935,
        "donation_date": "2020-01-31",
    },
    {
        "donor": "Carlita Howgill",
        "purpose": "Projects Support",
        "amount": 124274,
        "donation_date": "2020-07-08",
    },
    {
        "donor": "Larina Hanning",
        "purpose": "Church Support",
        "amount": 283825,
        "donation_date": "2023-02-19",
    },
    {
        "donor": "Egor Pilsbury",
        "purpose": "Projects Support",
        "amount": 47061,
        "donation_date": "2020-08-08",
    },
    {
        "donor": "Casie Booty",
        "purpose": "Projects Support",
        "amount": 918158,
        "donation_date": "2021-09-10",
    },
    {
        "donor": "Weylin Welsby",
        "purpose": "Projects Support",
        "amount": 612596,
        "donation_date": "2023-10-30",
    },
    {
        "donor": "Flss Duncan",
        "purpose": "Projects Support",
        "amount": 270831,
        "donation_date": "2020-03-04",
    },
    {
        "donor": "Rita Le Count",
        "purpose": "Projects Support",
        "amount": 35526,
        "donation_date": "2023-05-17",
    },
    {
        "donor": "Frederigo Marzelle",
        "purpose": "Projects Support",
        "amount": 119390,
        "donation_date": "2020-12-12",
    },
    {
        "donor": "Cirstoforo Ponceford",
        "purpose": "Church Support",
        "amount": 319097,
        "donation_date": "2022-02-28",
    },
    {
        "donor": "Horten Kirkland",
        "purpose": "Projects Support",
        "amount": 233158,
        "donation_date": "2021-05-03",
    },
    {
        "donor": "Sidonnie Heugh",
        "purpose": "Projects Support",
        "amount": 332554,
        "donation_date": "2022-04-12",
    },
    {
        "donor": "Doralin Kops",
        "purpose": "Church Support",
        "amount": 204757,
        "donation_date": "2023-10-06",
    },
    {
        "donor": "Kelwin Barsham",
        "purpose": "Projects Support",
        "amount": 439434,
        "donation_date": "2024-10-06",
    },
    {
        "donor": "Grissel Noweak",
        "purpose": "Projects Support",
        "amount": 804016,
        "donation_date": "2023-09-16",
    },
    {
        "donor": "Bernie Sute",
        "purpose": "Church Support",
        "amount": 665259,
        "donation_date": "2025-07-13",
    },
    {
        "donor": "Wilmette Krook",
        "purpose": "Projects Support",
        "amount": 744841,
        "donation_date": "2022-06-26",
    },
    {
        "donor": "Sela Kinchley",
        "purpose": "Projects Support",
        "amount": 185640,
        "donation_date": "2024-04-19",
    },
    {
        "donor": "Melvin Dunmore",
        "purpose": "Church Support",
        "amount": 766668,
        "donation_date": "2021-08-25",
    },
    {
        "donor": "Wyn Champneys",
        "purpose": "Church Support",
        "amount": 197249,
        "donation_date": "2024-06-15",
    },
    {
        "donor": "Rafaelita Aldersea",
        "purpose": "Projects Support",
        "amount": 741025,
        "donation_date": "2022-12-05",
    },
    {
        "donor": "Emogene Brucker",
        "purpose": "Church Support",
        "amount": 267298,
        "donation_date": "2020-03-17",
    },
    {
        "donor": "Alon Colclough",
        "purpose": "Church Support",
        "amount": 733369,
        "donation_date": "2020-03-09",
    },
    {
        "donor": "Arin Ilive",
        "purpose": "Church Support",
        "amount": 908062,
        "donation_date": "2023-03-16",
    },
    {
        "donor": "Isak Gumme",
        "purpose": "Projects Support",
        "amount": 463758,
        "donation_date": "2021-03-05",
    },
    {
        "donor": "Evey Creebo",
        "purpose": "Church Support",
        "amount": 806947,
        "donation_date": "2024-06-27",
    },
    {
        "donor": "Tilda Haddick",
        "purpose": "Projects Support",
        "amount": 473038,
        "donation_date": "2020-04-20",
    },
    {
        "donor": "Margalit Degli Abbati",
        "purpose": "Projects Support",
        "amount": 937216,
        "donation_date": "2025-04-14",
    },
    {
        "donor": "Marget Rivelon",
        "purpose": "Church Support",
        "amount": 475356,
        "donation_date": "2022-11-02",
    },
    {
        "donor": "Emiline Izzat",
        "purpose": "Projects Support",
        "amount": 976139,
        "donation_date": "2020-06-17",
    },
    {
        "donor": "Clyde Orae",
        "purpose": "Church Support",
        "amount": 806379,
        "donation_date": "2021-12-13",
    },
    {
        "donor": "Rhianon Cusack",
        "purpose": "Church Support",
        "amount": 954558,
        "donation_date": "2020-07-10",
    },
    {
        "donor": "Therese Salomon",
        "purpose": "Projects Support",
        "amount": 367721,
        "donation_date": "2021-04-03",
    },
    {
        "donor": "Tiena Renackowna",
        "purpose": "Church Support",
        "amount": 726446,
        "donation_date": "2025-06-14",
    },
    {
        "donor": "Ursula Oades",
        "purpose": "Projects Support",
        "amount": 772372,
        "donation_date": "2021-09-08",
    },
    {
        "donor": "Alexandra Booth",
        "purpose": "Projects Support",
        "amount": 331898,
        "donation_date": "2023-11-30",
    },
    {
        "donor": "Jeralee Childerhouse",
        "purpose": "Church Support",
        "amount": 748688,
        "donation_date": "2020-06-24",
    },
    {
        "donor": "Erina Maylott",
        "purpose": "Church Support",
        "amount": 342792,
        "donation_date": "2020-04-12",
    },
    {
        "donor": "Jamill Kenefick",
        "purpose": "Church Support",
        "amount": 380051,
        "donation_date": "2021-09-08",
    },
    {
        "donor": "Isabeau Lemery",
        "purpose": "Church Support",
        "amount": 842313,
        "donation_date": "2025-07-12",
    },
    {
        "donor": "Briano Juza",
        "purpose": "Projects Support",
        "amount": 456995,
        "donation_date": "2023-12-28",
    },
    {
        "donor": "Melba Tallman",
        "purpose": "Projects Support",
        "amount": 996644,
        "donation_date": "2021-03-22",
    },
    {
        "donor": "Merla Cropp",
        "purpose": "Projects Support",
        "amount": 567191,
        "donation_date": "2021-10-06",
    },
    {
        "donor": "Terrie Sumption",
        "purpose": "Projects Support",
        "amount": 599848,
        "donation_date": "2023-07-08",
    },
    {
        "donor": "Cecilius Degli Abbati",
        "purpose": "Church Support",
        "amount": 617550,
        "donation_date": "2023-01-03",
    },
    {
        "donor": "Maurizio Angrick",
        "purpose": "Church Support",
        "amount": 894848,
        "donation_date": "2024-05-30",
    },
    {
        "donor": "Sheila-kathryn Wahlberg",
        "purpose": "Church Support",
        "amount": 175170,
        "donation_date": "2020-05-24",
    },
    {
        "donor": "Evelyn Gauvin",
        "purpose": "Church Support",
        "amount": 683557,
        "donation_date": "2021-06-28",
    },
    {
        "donor": "Levy Vanni",
        "purpose": "Projects Support",
        "amount": 419355,
        "donation_date": "2024-05-02",
    },
    {
        "donor": "Joni Othen",
        "purpose": "Projects Support",
        "amount": 816250,
        "donation_date": "2024-03-11",
    },
    {
        "donor": "Oralle Dodsworth",
        "purpose": "Projects Support",
        "amount": 884589,
        "donation_date": "2023-01-28",
    },
    {
        "donor": "Suzanne Chillingsworth",
        "purpose": "Church Support",
        "amount": 564971,
        "donation_date": "2023-06-22",
    },
    {
        "donor": "Meridel Wildber",
        "purpose": "Projects Support",
        "amount": 623027,
        "donation_date": "2022-09-23",
    },
    {
        "donor": "Coriss MacCrossan",
        "purpose": "Projects Support",
        "amount": 890548,
        "donation_date": "2022-12-04",
    },
    {
        "donor": "Dorothee Ferrotti",
        "purpose": "Church Support",
        "amount": 621085,
        "donation_date": "2020-05-04",
    },
    {
        "donor": "Keenan Wrotham",
        "purpose": "Projects Support",
        "amount": 837435,
        "donation_date": "2021-12-20",
    },
    {
        "donor": "Rob McAw",
        "purpose": "Church Support",
        "amount": 633246,
        "donation_date": "2021-07-30",
    },
    {
        "donor": "Iggie Glasper",
        "purpose": "Church Support",
        "amount": 174153,
        "donation_date": "2020-05-24",
    },
    {
        "donor": "See De Filippis",
        "purpose": "Church Support",
        "amount": 260707,
        "donation_date": "2021-02-13",
    },
    {
        "donor": "Killian Jori",
        "purpose": "Church Support",
        "amount": 714133,
        "donation_date": "2024-02-28",
    },
    {
        "donor": "Dagny Whitby",
        "purpose": "Projects Support",
        "amount": 964706,
        "donation_date": "2022-04-03",
    },
    {
        "donor": "Aldric Corps",
        "purpose": "Church Support",
        "amount": 600068,
        "donation_date": "2022-04-06",
    },
    {
        "donor": "Orran Fullagar",
        "purpose": "Church Support",
        "amount": 103973,
        "donation_date": "2023-01-09",
    },
    {
        "donor": "Pepita Wibrew",
        "purpose": "Projects Support",
        "amount": 739978,
        "donation_date": "2023-10-01",
    },
    {
        "donor": "Osborne Wayon",
        "purpose": "Church Support",
        "amount": 28400,
        "donation_date": "2021-05-26",
    },
    {
        "donor": "Sherwynd Soggee",
        "purpose": "Projects Support",
        "amount": 613342,
        "donation_date": "2025-04-05",
    },
    {
        "donor": "Nani Crossman",
        "purpose": "Projects Support",
        "amount": 878138,
        "donation_date": "2023-11-16",
    },
    {
        "donor": "Felix Challenor",
        "purpose": "Church Support",
        "amount": 123740,
        "donation_date": "2024-04-27",
    },
    {
        "donor": "Elsbeth Grimm",
        "purpose": "Projects Support",
        "amount": 267808,
        "donation_date": "2022-04-11",
    },
    {
        "donor": "Burlie Giorio",
        "purpose": "Church Support",
        "amount": 35025,
        "donation_date": "2020-12-02",
    },
    {
        "donor": "Ninette Romanet",
        "purpose": "Projects Support",
        "amount": 773647,
        "donation_date": "2023-07-30",
    },
    {
        "donor": "Garrick Covill",
        "purpose": "Projects Support",
        "amount": 66529,
        "donation_date": "2021-05-18",
    },
    {
        "donor": "Roanne Perle",
        "purpose": "Projects Support",
        "amount": 359092,
        "donation_date": "2024-08-16",
    },
    {
        "donor": "Iver Sealeaf",
        "purpose": "Church Support",
        "amount": 151261,
        "donation_date": "2024-01-13",
    },
    {
        "donor": "Horatia Fearney",
        "purpose": "Church Support",
        "amount": 42928,
        "donation_date": "2024-02-01",
    },
    {
        "donor": "Katalin Angeau",
        "purpose": "Projects Support",
        "amount": 431993,
        "donation_date": "2024-06-19",
    },
    {
        "donor": "Katrinka Mateuszczyk",
        "purpose": "Church Support",
        "amount": 393625,
        "donation_date": "2025-05-02",
    },
    {
        "donor": "Freemon Chafney",
        "purpose": "Church Support",
        "amount": 923325,
        "donation_date": "2022-05-31",
    },
    {
        "donor": "Gunner Basketfield",
        "purpose": "Church Support",
        "amount": 366290,
        "donation_date": "2021-07-12",
    },
    {
        "donor": "Levy Elie",
        "purpose": "Church Support",
        "amount": 441192,
        "donation_date": "2020-10-14",
    },
    {
        "donor": "Paulie Jaan",
        "purpose": "Church Support",
        "amount": 452147,
        "donation_date": "2024-07-30",
    },
    {
        "donor": "Sinclair Heims",
        "purpose": "Church Support",
        "amount": 410660,
        "donation_date": "2024-09-09",
    },
    {
        "donor": "Rick Stockey",
        "purpose": "Projects Support",
        "amount": 232904,
        "donation_date": "2021-11-19",
    },
    {
        "donor": "Herve Binding",
        "purpose": "Projects Support",
        "amount": 238376,
        "donation_date": "2021-08-22",
    },
    {
        "donor": "Salomone Twidle",
        "purpose": "Projects Support",
        "amount": 635149,
        "donation_date": "2025-06-21",
    },
    {
        "donor": "Vaughan Roubay",
        "purpose": "Church Support",
        "amount": 114272,
        "donation_date": "2024-03-24",
    },
    {
        "donor": "Katya Shurmer",
        "purpose": "Church Support",
        "amount": 908264,
        "donation_date": "2023-01-03",
    },
    {
        "donor": "Bartie Wanell",
        "purpose": "Projects Support",
        "amount": 979589,
        "donation_date": "2020-12-01",
    },
    {
        "donor": "Charlot Dalgetty",
        "purpose": "Projects Support",
        "amount": 117848,
        "donation_date": "2020-04-30",
    },
    {
        "donor": "Karlyn Lanney",
        "purpose": "Projects Support",
        "amount": 487489,
        "donation_date": "2020-09-20",
    },
    {
        "donor": "Tatiana Kubicki",
        "purpose": "Projects Support",
        "amount": 169473,
        "donation_date": "2021-06-12",
    },
    {
        "donor": "Ingrid Bartelli",
        "purpose": "Church Support",
        "amount": 20497,
        "donation_date": "2020-04-16",
    },
    {
        "donor": "Nick De Hooch",
        "purpose": "Projects Support",
        "amount": 778400,
        "donation_date": "2021-06-22",
    },
    {
        "donor": "Eartha Joslow",
        "purpose": "Church Support",
        "amount": 562196,
        "donation_date": "2020-01-01",
    },
    {
        "donor": "Lammond Frawley",
        "purpose": "Church Support",
        "amount": 751885,
        "donation_date": "2024-06-11",
    },
    {
        "donor": "Gauthier Ghiriardelli",
        "purpose": "Church Support",
        "amount": 536413,
        "donation_date": "2024-02-02",
    },
    {
        "donor": "Wayne Corney",
        "purpose": "Projects Support",
        "amount": 340991,
        "donation_date": "2022-12-04",
    },
    {
        "donor": "Madalena Heeney",
        "purpose": "Projects Support",
        "amount": 290611,
        "donation_date": "2021-09-14",
    },
    {
        "donor": "Malissia Dalrymple",
        "purpose": "Church Support",
        "amount": 410862,
        "donation_date": "2024-05-24",
    },
    {
        "donor": "Korey Cases",
        "purpose": "Projects Support",
        "amount": 691826,
        "donation_date": "2022-10-28",
    },
    {
        "donor": "Lennard Skeermer",
        "purpose": "Projects Support",
        "amount": 737498,
        "donation_date": "2025-07-26",
    },
    {
        "donor": "Avie O'Rafferty",
        "purpose": "Church Support",
        "amount": 421720,
        "donation_date": "2021-04-17",
    },
    {
        "donor": "Elaina Marcum",
        "purpose": "Church Support",
        "amount": 741067,
        "donation_date": "2022-02-08",
    },
    {
        "donor": "Osborne Costock",
        "purpose": "Projects Support",
        "amount": 699257,
        "donation_date": "2023-05-17",
    },
    {
        "donor": "Baxter Scholz",
        "purpose": "Projects Support",
        "amount": 977282,
        "donation_date": "2024-01-07",
    },
    {
        "donor": "Filippo Turneaux",
        "purpose": "Church Support",
        "amount": 119692,
        "donation_date": "2022-10-27",
    },
    {
        "donor": "Valli Robison",
        "purpose": "Projects Support",
        "amount": 95327,
        "donation_date": "2024-04-10",
    },
    {
        "donor": "Charmaine Cumberpatch",
        "purpose": "Projects Support",
        "amount": 391519,
        "donation_date": "2024-01-27",
    },
    {
        "donor": "Ingar Knightsbridge",
        "purpose": "Church Support",
        "amount": 677151,
        "donation_date": "2024-03-25",
    },
    {
        "donor": "Micaela Blatcher",
        "purpose": "Projects Support",
        "amount": 227002,
        "donation_date": "2022-06-12",
    },
    {
        "donor": "Eachelle Sambath",
        "purpose": "Projects Support",
        "amount": 801114,
        "donation_date": "2021-09-28",
    },
    {
        "donor": "Constantia Ende",
        "purpose": "Church Support",
        "amount": 826256,
        "donation_date": "2022-10-29",
    },
    {
        "donor": "Illa Trewett",
        "purpose": "Church Support",
        "amount": 195505,
        "donation_date": "2022-10-08",
    },
    {
        "donor": "Darby Doerren",
        "purpose": "Projects Support",
        "amount": 583140,
        "donation_date": "2024-04-13",
    },
    {
        "donor": "Bonita Klimczak",
        "purpose": "Church Support",
        "amount": 846864,
        "donation_date": "2022-02-18",
    },
    {
        "donor": "Theodoric Geely",
        "purpose": "Projects Support",
        "amount": 279580,
        "donation_date": "2021-04-04",
    },
    {
        "donor": "Elwira Morrow",
        "purpose": "Projects Support",
        "amount": 337445,
        "donation_date": "2023-11-27",
    },
    {
        "donor": "My Durdle",
        "purpose": "Church Support",
        "amount": 733351,
        "donation_date": "2020-03-12",
    },
    {
        "donor": "Verla Elmore",
        "purpose": "Church Support",
        "amount": 859715,
        "donation_date": "2022-04-16",
    },
    {
        "donor": "Osbert Henrichsen",
        "purpose": "Projects Support",
        "amount": 820373,
        "donation_date": "2021-08-02",
    },
    {
        "donor": "Fidelio Ollcott",
        "purpose": "Church Support",
        "amount": 975881,
        "donation_date": "2025-05-12",
    },
    {
        "donor": "Pegeen Castillo",
        "purpose": "Church Support",
        "amount": 877061,
        "donation_date": "2022-09-23",
    },
    {
        "donor": "Angus Tuma",
        "purpose": "Projects Support",
        "amount": 159198,
        "donation_date": "2022-10-22",
    },
    {
        "donor": "Shaine Devonside",
        "purpose": "Church Support",
        "amount": 882444,
        "donation_date": "2024-01-11",
    },
    {
        "donor": "Sonnie Blacklidge",
        "purpose": "Projects Support",
        "amount": 320735,
        "donation_date": "2022-08-03",
    },
    {
        "donor": "Peta Cozens",
        "purpose": "Projects Support",
        "amount": 395790,
        "donation_date": "2025-07-14",
    },
    {
        "donor": "April Prazer",
        "purpose": "Church Support",
        "amount": 546113,
        "donation_date": "2023-10-08",
    },
    {
        "donor": "Cosette Welfair",
        "purpose": "Church Support",
        "amount": 993202,
        "donation_date": "2021-07-11",
    },
    {
        "donor": "Guilbert Dewdney",
        "purpose": "Projects Support",
        "amount": 541136,
        "donation_date": "2020-01-25",
    },
    {
        "donor": "Kristopher Cluett",
        "purpose": "Projects Support",
        "amount": 72934,
        "donation_date": "2022-10-02",
    },
    {
        "donor": "Shellie McBryde",
        "purpose": "Church Support",
        "amount": 232800,
        "donation_date": "2023-05-08",
    },
    {
        "donor": "Orelie Crauford",
        "purpose": "Church Support",
        "amount": 304706,
        "donation_date": "2021-12-21",
    },
    {
        "donor": "Anallise Elner",
        "purpose": "Church Support",
        "amount": 244341,
        "donation_date": "2023-04-21",
    },
    {
        "donor": "Jolene Seeviour",
        "purpose": "Projects Support",
        "amount": 346460,
        "donation_date": "2021-11-13",
    },
    {
        "donor": "Felix Derrell",
        "purpose": "Projects Support",
        "amount": 662810,
        "donation_date": "2020-08-08",
    },
    {
        "donor": "Angelico Georgiev",
        "purpose": "Projects Support",
        "amount": 231788,
        "donation_date": "2024-11-09",
    },
    {
        "donor": "Leo Aldington",
        "purpose": "Church Support",
        "amount": 574195,
        "donation_date": "2020-11-17",
    },
    {
        "donor": "Roddie Deveril",
        "purpose": "Church Support",
        "amount": 115027,
        "donation_date": "2022-03-22",
    },
    {
        "donor": "Beth Gilbane",
        "purpose": "Church Support",
        "amount": 372622,
        "donation_date": "2023-02-11",
    },
    {
        "donor": "Hyacintha Lamerton",
        "purpose": "Projects Support",
        "amount": 467724,
        "donation_date": "2022-03-29",
    },
    {
        "donor": "Nonie Damerell",
        "purpose": "Projects Support",
        "amount": 292432,
        "donation_date": "2023-09-22",
    },
    {
        "donor": "Gerrie Hambers",
        "purpose": "Projects Support",
        "amount": 414464,
        "donation_date": "2020-08-18",
    },
    {
        "donor": "Hynda Trollope",
        "purpose": "Church Support",
        "amount": 709600,
        "donation_date": "2021-12-08",
    },
    {
        "donor": "Kathye Pellamonuten",
        "purpose": "Church Support",
        "amount": 825653,
        "donation_date": "2022-05-08",
    },
    {
        "donor": "Mile Neilands",
        "purpose": "Projects Support",
        "amount": 974331,
        "donation_date": "2022-04-22",
    },
    {
        "donor": "Teresita Vasilechko",
        "purpose": "Church Support",
        "amount": 954152,
        "donation_date": "2021-06-09",
    },
    {
        "donor": "Loralie Kliner",
        "purpose": "Church Support",
        "amount": 638019,
        "donation_date": "2022-01-01",
    },
    {
        "donor": "Artemus Hawket",
        "purpose": "Projects Support",
        "amount": 146932,
        "donation_date": "2020-11-27",
    },
    {
        "donor": "Cordelie Schoular",
        "purpose": "Church Support",
        "amount": 909119,
        "donation_date": "2023-08-17",
    },
    {
        "donor": "Osmond Hallahan",
        "purpose": "Projects Support",
        "amount": 210980,
        "donation_date": "2022-06-14",
    },
    {
        "donor": "Lora Bensusan",
        "purpose": "Church Support",
        "amount": 642324,
        "donation_date": "2024-03-11",
    },
    {
        "donor": "Monica Juorio",
        "purpose": "Church Support",
        "amount": 255933,
        "donation_date": "2020-12-30",
    },
    {
        "donor": "Jeremiah Hobbema",
        "purpose": "Projects Support",
        "amount": 237641,
        "donation_date": "2022-04-15",
    },
    {
        "donor": "Anastasia Prettjohn",
        "purpose": "Projects Support",
        "amount": 623590,
        "donation_date": "2023-11-15",
    },
    {
        "donor": "Rivkah Priestman",
        "purpose": "Church Support",
        "amount": 509225,
        "donation_date": "2022-06-28",
    },
    {
        "donor": "Mateo Adriaan",
        "purpose": "Projects Support",
        "amount": 156276,
        "donation_date": "2024-07-20",
    },
    {
        "donor": "Calli Kristiansen",
        "purpose": "Church Support",
        "amount": 629863,
        "donation_date": "2020-04-20",
    },
    {
        "donor": "Winny Genty",
        "purpose": "Church Support",
        "amount": 308772,
        "donation_date": "2021-02-14",
    },
    {
        "donor": "Joela Rubbert",
        "purpose": "Projects Support",
        "amount": 928695,
        "donation_date": "2024-06-14",
    },
    {
        "donor": "Genni Chivrall",
        "purpose": "Projects Support",
        "amount": 760078,
        "donation_date": "2022-04-21",
    },
    {
        "donor": "Dale Juggings",
        "purpose": "Projects Support",
        "amount": 141003,
        "donation_date": "2023-10-27",
    },
    {
        "donor": "Dorine Moatt",
        "purpose": "Projects Support",
        "amount": 253414,
        "donation_date": "2021-01-06",
    },
    {
        "donor": "Sheilakathryn Head",
        "purpose": "Church Support",
        "amount": 180953,
        "donation_date": "2021-07-29",
    },
    {
        "donor": "Larissa Henniger",
        "purpose": "Projects Support",
        "amount": 869531,
        "donation_date": "2022-06-19",
    },
    {
        "donor": "Grayce Espinay",
        "purpose": "Church Support",
        "amount": 361361,
        "donation_date": "2021-04-10",
    },
    {
        "donor": "Briano Dury",
        "purpose": "Church Support",
        "amount": 886771,
        "donation_date": "2023-01-31",
    },
    {
        "donor": "Tish Varcoe",
        "purpose": "Church Support",
        "amount": 460004,
        "donation_date": "2024-10-28",
    },
    {
        "donor": "Benedikta Haste",
        "purpose": "Projects Support",
        "amount": 360989,
        "donation_date": "2022-09-27",
    },
    {
        "donor": "Mala Gummory",
        "purpose": "Projects Support",
        "amount": 442578,
        "donation_date": "2021-11-06",
    },
    {
        "donor": "Hamil Ghiron",
        "purpose": "Church Support",
        "amount": 853426,
        "donation_date": "2021-09-23",
    },
    {
        "donor": "Asia Bennington",
        "purpose": "Church Support",
        "amount": 64651,
        "donation_date": "2021-03-23",
    },
    {
        "donor": "Jonell Jenkins",
        "purpose": "Projects Support",
        "amount": 601550,
        "donation_date": "2020-07-18",
    },
    {
        "donor": "Ives Aleavy",
        "purpose": "Projects Support",
        "amount": 758148,
        "donation_date": "2024-10-20",
    },
    {
        "donor": "Brita Bosence",
        "purpose": "Church Support",
        "amount": 33160,
        "donation_date": "2024-12-11",
    },
    {
        "donor": "Hiram Gillow",
        "purpose": "Projects Support",
        "amount": 563781,
        "donation_date": "2025-04-04",
    },
    {
        "donor": "Wye Clacson",
        "purpose": "Projects Support",
        "amount": 100380,
        "donation_date": "2025-01-03",
    },
    {
        "donor": "Aubrie Moy",
        "purpose": "Projects Support",
        "amount": 717080,
        "donation_date": "2022-04-26",
    },
    {
        "donor": "Amelita Pioch",
        "purpose": "Church Support",
        "amount": 390417,
        "donation_date": "2022-10-27",
    },
    {
        "donor": "Ramon Errichiello",
        "purpose": "Church Support",
        "amount": 255217,
        "donation_date": "2024-07-05",
    },
    {
        "donor": "Tabatha Tarry",
        "purpose": "Church Support",
        "amount": 391882,
        "donation_date": "2024-09-16",
    },
    {
        "donor": "Vittorio Drinnan",
        "purpose": "Projects Support",
        "amount": 476946,
        "donation_date": "2022-03-24",
    },
]

from decimal import Decimal


def load_donations():
    for record in records:
        donor = record.get("donor")
        purpose = record.get("purpose")
        amount = record.get("amount")
        donation_date = record.get("donation_date")

        date_obj = format_date(donation_date)
        month_name = get_month_name(date_obj.month)
        year = date_obj.year

        donation = ChurchDonation.objects.create(
            donor=donor,
            purpose=purpose,
            amount=amount,
            donation_date=donation_date,
            captured_by=user,
            month=month_name,
            year=year,
        )

        ChurchLedger.objects.create(
            name=f"{donation.donor} Donation",
            description=f"Donation: {donation.purpose}",
            amount=Decimal(amount),
            direction="Income",
            user=user,
            month=month_name,
            year=year,
            transaction_date=donation_date,
        )
