# Generated by Django 5.1.2 on 2025-05-17 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(choices=[('Church Member', 'Church Member'), ('Pastor', 'Pastor'), ('Men Department Leader', 'Men Department Leader'), ('Women Department Leader', 'Women Department Leader'), ('Teens Department Leader', 'Teens Department Leader'), ('Church Secretary', 'Church Secretary'), ('Church Treasurer', 'Church Treasurer')], default='Church Member', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=255)),
                ('member_since', models.DateField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
