# Generated by Django 5.2.5 on 2025-09-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membership", "0001_initial"),
        ("sections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="churchsections",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sections.section",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchmembers",
                to="membership.branch",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.department",
            ),
        ),
    ]
