# Generated by Django 5.2.5 on 2025-09-22 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membership", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="membership.member"
            ),
        ),
        migrations.AddField(
            model_name="membergroup",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.branch",
            ),
        ),
        migrations.AddField(
            model_name="membergroup",
            name="chairperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chaired_groups",
                to="membership.member",
            ),
        ),
        migrations.AddField(
            model_name="membergroup",
            name="secretary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secretary_groups",
                to="membership.member",
            ),
        ),
        migrations.AddField(
            model_name="membergroup",
            name="treasurer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treasurer_groups",
                to="membership.member",
            ),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groupmembers",
                to="membership.membergroup",
            ),
        ),
        migrations.AddField(
            model_name="serviceattendance",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="membership.member"
            ),
        ),
        migrations.AddField(
            model_name="serviceattendance",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="membership.churchservice",
            ),
        ),
    ]
