# Generated by Django 5.2.5 on 2025-09-22 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch",
            old_name="churchsections",
            new_name="section",
        ),
    ]
