# Generated by Django 5.1.2 on 2025-05-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_member_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
