# Generated by Django 5.2.5 on 2025-09-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0004_rename_churchsections_branch_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAttendanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("month", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("total_present", models.IntegerField(default=0)),
                ("service_date", models.DateField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="membership.churchservice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
