# Generated by Django 5.2.5 on 2025-09-23 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0005_serviceattendancemetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceattendancemetric",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="membership.branch",
            ),
        ),
    ]
