# Generated by Django 5.1.2 on 2025-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0005_branch_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
