# Generated by Django 5.1.2 on 2025-08-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0006_churchservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchservice",
            name="service_day",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
