# Generated by Django 5.2.5 on 2025-09-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0006_serviceattendancemetric_branch"),
        ("payments", "0003_alter_memberoffering_service_alter_offering_service"),
        ("users", "0003_alter_visitor_church_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceattendancemetric",
            name="service",
        ),
        migrations.RemoveField(
            model_name="serviceattendance",
            name="service",
        ),
        migrations.RemoveField(
            model_name="serviceattendance",
            name="member",
        ),
        migrations.RemoveField(
            model_name="serviceattendancemetric",
            name="branch",
        ),
        migrations.DeleteModel(
            name="ChurchService",
        ),
        migrations.DeleteModel(
            name="ServiceAttendance",
        ),
        migrations.DeleteModel(
            name="ServiceAttendanceMetric",
        ),
    ]
