# Generated by Django 5.1.2 on 2025-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0007_churchservice_service_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="churchservice",
            name="service_day",
            field=models.CharField(default="Sunday", max_length=255),
        ),
    ]
