# Generated by Django 5.2.5 on 2025-10-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0008_branch_pastor"),
        ("sections", "0003_section_has_presbyter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sectionbranches",
                to="sections.section",
            ),
        ),
    ]
