# Generated by Django 5.2.5 on 2025-10-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0009_alter_branch_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="pastor",
        ),
    ]
