# Generated by Django 5.2.5 on 2025-09-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0010_membergroup_groupmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="membergroup",
            name="chairperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chaired_groups",
                to="membership.member",
            ),
        ),
        migrations.AddField(
            model_name="membergroup",
            name="secretary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secretary_groups",
                to="membership.member",
            ),
        ),
        migrations.AddField(
            model_name="membergroup",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="membergroup",
            name="treasurer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treasurer_groups",
                to="membership.member",
            ),
        ),
    ]
