# Generated by Django 5.2.5 on 2025-10-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0010_remove_branch_pastor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membergroup",
            name="chairperson",
        ),
        migrations.RemoveField(
            model_name="membergroup",
            name="secretary",
        ),
        migrations.RemoveField(
            model_name="membergroup",
            name="treasurer",
        ),
    ]
