# Generated by Django 5.2.5 on 2025-09-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0011_membergroup_chairperson_membergroup_secretary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="role",
            field=models.CharField(default="Member", max_length=255),
        ),
    ]
