# Generated by Django 5.2.5 on 2025-09-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0012_groupmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupmember",
            name="date_joined",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Suspended", "Suspended"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
