# Generated by Django 5.2.5 on 2025-09-03 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0013_groupmember_date_joined_groupmember_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmember",
            name="date_joined",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
