# Generated by Django 5.2.5 on 2025-09-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0014_alter_groupmember_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membergroup",
            name="department",
        ),
    ]
