# Generated by Django 5.2.5 on 2025-09-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0015_remove_membergroup_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchservice",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=50,
            ),
        ),
    ]
