# Generated by Django 5.2.5 on 2025-09-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0016_churchservice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceattendance",
            name="month",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="serviceattendance",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
