# Generated by Django 5.2.5 on 2025-10-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_marriagerequest_request_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baptismrequest",
            name="request_type",
            field=models.CharField(
                choices=[("Member", "Member"), ("Non-Member", "Non-Member")],
                default="Member",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="burialrequest",
            name="request_type",
            field=models.CharField(
                choices=[("Member", "Member"), ("Non-Member", "Non-Member")],
                default="Member",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="prayerrequest",
            name="request_type",
            field=models.CharField(
                choices=[("Member", "Member"), ("Non-Member", "Non-Member")],
                default="Member",
                max_length=255,
            ),
        ),
    ]
