# Generated by Django 5.2.5 on 2025-10-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_alter_baptismrequest_request_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baptismrequest",
            name="request_date",
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="burialrequest",
            name="request_date",
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="request_date",
            field=models.DateField(max_length=255, null=True),
        ),
    ]
