# Generated by Django 5.2.5 on 2025-10-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_baptismrequest_request_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baptismrequest",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="burialrequest",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prayerrequest",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=255,
                null=True,
            ),
        ),
    ]
