# Generated by Django 5.2.5 on 2025-10-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0005_alter_baptismrequest_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baptismrequest",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="burialrequest",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="prayerrequest",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
