# Generated by Django 5.2.5 on 2025-10-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0006_alter_baptismrequest_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baptismrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Complete", "Complete"),
                    ("Declined", "Declined"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="burialrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Complete", "Complete"),
                    ("Declined", "Declined"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="marriagerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Complete", "Complete"),
                    ("Declined", "Declined"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="prayerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Complete", "Complete"),
                    ("Declined", "Declined"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
