# Generated by Django 5.2.5 on 2025-10-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0007_alter_baptismrequest_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="churchmeetingattendance",
            name="member",
        ),
        migrations.AddField(
            model_name="churchmeetingattendance",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="churchmeetingattendance",
            name="first_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="churchmeetingattendance",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="churchmeetingattendance",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="churchmeetingattendance",
            name="role",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
