# Generated by Django 5.2.5 on 2025-10-26 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_churchrole"),
        ("scheduling", "0008_remove_churchmeetingattendance_member_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="church",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.church"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="baptismrequest",
            name="church",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.church"
            ),
        ),
        migrations.AddField(
            model_name="baptismrequest",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="baptismrequest",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="burialrequest",
            name="church",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.church"
            ),
        ),
        migrations.AddField(
            model_name="burialrequest",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="burialrequest",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="churchmeeting",
            name="church",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.church"
            ),
        ),
        migrations.AddField(
            model_name="churchmeeting",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="churchmeeting",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="churchmeeting",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="churchmeetingattendance",
            name="church",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.church"
            ),
        ),
        migrations.AddField(
            model_name="churchmeetingattendance",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="churchmeetingattendance",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="marriagerequest",
            name="church",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.church"
            ),
        ),
        migrations.AddField(
            model_name="marriagerequest",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="marriagerequest",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="church",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.church"
            ),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="month",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="year",
            field=models.CharField(max_length=4, null=True),
        ),
    ]
