# Generated by Django 5.2.5 on 2025-10-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0009_appointment_church_appointment_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchmeeting",
            name="status",
            field=models.CharField(default="Scheduled", max_length=255),
        ),
    ]
