# Generated by Django 5.2.5 on 2025-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0010_churchmeeting_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchmeetingattendance",
            name="gender",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
