# Generated by Django 5.2.5 on 2025-10-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0011_churchmeetingattendance_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="churchmeetingattendance",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="churchmeetingattendances",
                to="scheduling.churchmeeting",
            ),
        ),
    ]
