# Generated by Django 5.2.5 on 2025-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0012_alter_churchmeetingattendance_meeting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="closed",
        ),
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(default="Pending", max_length=255),
        ),
    ]
