# Generated by Django 5.2.5 on 2025-10-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0013_remove_appointment_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
