# Generated by Django 5.2.5 on 2025-10-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_churchofferingchannel"),
        ("scheduling", "0014_appointment_appointment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="burialrequest",
            name="church",
        ),
        migrations.RemoveField(
            model_name="marriagerequest",
            name="church",
        ),
        migrations.RemoveField(
            model_name="prayerrequest",
            name="church",
        ),
        migrations.CreateModel(
            name="ChurchMemberRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Wedding", "Wedding"),
                            ("Burial", "Burial"),
                            ("Prayer", "Prayer"),
                            ("Baptism", "Baptism"),
                        ],
                        max_length=255,
                    ),
                ),
                ("groom_first_name", models.CharField(max_length=255, null=True)),
                ("groom_last_name", models.CharField(max_length=255, null=True)),
                ("bride_first_name", models.CharField(max_length=255, null=True)),
                ("bride_last_name", models.CharField(max_length=255, null=True)),
                ("wedding_date", models.DateField(max_length=255, null=True)),
                ("wedding_location", models.CharField(max_length=255, null=True)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("Member", "Member"), ("Non-Member", "Non-Member")],
                        default="Member",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Complete", "Complete"),
                            ("Declined", "Declined"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=255,
                    ),
                ),
                ("request_date", models.DateField(max_length=255, null=True)),
                ("phone_number", models.CharField(max_length=255, null=True)),
                ("month", models.CharField(max_length=255, null=True)),
                ("year", models.CharField(max_length=4, null=True)),
                (
                    "church",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.church",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="BaptismRequest",
        ),
        migrations.DeleteModel(
            name="BurialRequest",
        ),
        migrations.DeleteModel(
            name="MarriageRequest",
        ),
        migrations.DeleteModel(
            name="PrayerRequest",
        ),
    ]
