from apps.core.models import Country


countries_currencies = [
    {"country": "Afghanistan", "currency_name": "Afghan Afghani", "currency_code": "AFN"},
    {"country": "Albania", "currency_name": "Albanian Lek", "currency_code": "ALL"},
    {"country": "Algeria", "currency_name": "Algerian Dinar", "currency_code": "DZD"},
    {"country": "Andorra", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Angola", "currency_name": "Angolan Kwanza", "currency_code": "AOA"},
    {"country": "Antigua and Barbuda", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    {"country": "Argentina", "currency_name": "Argentine Peso", "currency_code": "ARS"},
    {"country": "Armenia", "currency_name": "Armenian Dram", "currency_code": "AMD"},
    {"country": "Australia", "currency_name": "Australian Dollar", "currency_code": "AUD"},
    {"country": "Austria", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Azerbaijan", "currency_name": "Azerbaijani Manat", "currency_code": "AZN"},
    {"country": "Bahamas", "currency_name": "Bahamian Dollar", "currency_code": "BSD"},
    {"country": "Bahrain", "currency_name": "Bahraini Dinar", "currency_code": "BHD"},
    {"country": "Bangladesh", "currency_name": "Bangladeshi Taka", "currency_code": "BDT"},
    {"country": "Barbados", "currency_name": "Barbadian Dollar", "currency_code": "BBD"},
    {"country": "Belarus", "currency_name": "Belarusian Ruble", "currency_code": "BYN"},
    {"country": "Belgium", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Belize", "currency_name": "Belize Dollar", "currency_code": "BZD"},
    {"country": "Benin", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    {"country": "Bhutan", "currency_name": "Bhutanese Ngultrum", "currency_code": "BTN"},
    {"country": "Bolivia", "currency_name": "Bolivian Boliviano", "currency_code": "BOB"},
    {"country": "Bosnia and Herzegovina", "currency_name": "Bosnia and Herzegovina Convertible Mark", "currency_code": "BAM"},
    {"country": "Botswana", "currency_name": "Botswana Pula", "currency_code": "BWP"},
    {"country": "Brazil", "currency_name": "Brazilian Real", "currency_code": "BRL"},
    {"country": "Brunei", "currency_name": "Brunei Dollar", "currency_code": "BND"},
    {"country": "Bulgaria", "currency_name": "Bulgarian Lev", "currency_code": "BGN"},
    {"country": "Burkina Faso", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    {"country": "Burundi", "currency_name": "Burundian Franc", "currency_code": "BIF"},
    {"country": "Cabo Verde", "currency_name": "Cape Verdean Escudo", "currency_code": "CVE"},
    {"country": "Cambodia", "currency_name": "Cambodian Riel", "currency_code": "KHR"},
    {"country": "Cameroon", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    {"country": "Canada", "currency_name": "Canadian Dollar", "currency_code": "CAD"},
    {"country": "Chad", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    {"country": "Chile", "currency_name": "Chilean Peso", "currency_code": "CLP"},
    {"country": "China", "currency_name": "Chinese Yuan", "currency_code": "CNY"},
    {"country": "Colombia", "currency_name": "Colombian Peso", "currency_code": "COP"},
    {"country": "Comoros", "currency_name": "Comorian Franc", "currency_code": "KMF"},
    {"country": "Congo (Brazzaville)", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    {"country": "Congo (Kinshasa)", "currency_name": "Congolese Franc", "currency_code": "CDF"},
    {"country": "Costa Rica", "currency_name": "Costa Rican Colón", "currency_code": "CRC"},
    {"country": "Croatia", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Cuba", "currency_name": "Cuban Peso", "currency_code": "CUP"},
    {"country": "Cyprus", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Czech Republic", "currency_name": "Czech Koruna", "currency_code": "CZK"},
    {"country": "Denmark", "currency_name": "Danish Krone", "currency_code": "DKK"},
    {"country": "Djibouti", "currency_name": "Djiboutian Franc", "currency_code": "DJF"},
    {"country": "Dominican Republic", "currency_name": "Dominican Peso", "currency_code": "DOP"},
    {"country": "Ecuador", "currency_name": "US Dollar", "currency_code": "USD"},
    {"country": "Egypt", "currency_name": "Egyptian Pound", "currency_code": "EGP"},
    {"country": "El Salvador", "currency_name": "US Dollar", "currency_code": "USD"},
    {"country": "Equatorial Guinea", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    {"country": "Eritrea", "currency_name": "Eritrean Nakfa", "currency_code": "ERN"},
    {"country": "Estonia", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Eswatini", "currency_name": "Swazi Lilangeni", "currency_code": "SZL"},
    {"country": "Ethiopia", "currency_name": "Ethiopian Birr", "currency_code": "ETB"},
    {"country": "Fiji", "currency_name": "Fijian Dollar", "currency_code": "FJD"},
    {"country": "Finland", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "France", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Gabon", "currency_name": "Central African CFA Franc", "currency_code": "XAF"},
    {"country": "Gambia", "currency_name": "Gambian Dalasi", "currency_code": "GMD"},
    {"country": "Georgia", "currency_name": "Georgian Lari", "currency_code": "GEL"},
    {"country": "Germany", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Ghana", "currency_name": "Ghanaian Cedi", "currency_code": "GHS"},
    {"country": "Greece", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Grenada", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    {"country": "Guatemala", "currency_name": "Guatemalan Quetzal", "currency_code": "GTQ"},
    {"country": "Guinea", "currency_name": "Guinean Franc", "currency_code": "GNF"},
    {"country": "Guyana", "currency_name": "Guyanese Dollar", "currency_code": "GYD"},
    {"country": "Haiti", "currency_name": "Haitian Gourde", "currency_code": "HTG"},
    {"country": "Honduras", "currency_name": "Honduran Lempira", "currency_code": "HNL"},
    {"country": "Hong Kong", "currency_name": "Hong Kong Dollar", "currency_code": "HKD"},
    {"country": "Hungary", "currency_name": "Hungarian Forint", "currency_code": "HUF"},
    {"country": "Iceland", "currency_name": "Icelandic Króna", "currency_code": "ISK"},
    {"country": "India", "currency_name": "Indian Rupee", "currency_code": "INR"},
    {"country": "Indonesia", "currency_name": "Indonesian Rupiah", "currency_code": "IDR"},
    {"country": "Iran", "currency_name": "Iranian Rial", "currency_code": "IRR"},
    {"country": "Iraq", "currency_name": "Iraqi Dinar", "currency_code": "IQD"},
    {"country": "Ireland", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Israel", "currency_name": "Israeli New Shekel", "currency_code": "ILS"},
    {"country": "Italy", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Jamaica", "currency_name": "Jamaican Dollar", "currency_code": "JMD"},
    {"country": "Japan", "currency_name": "Japanese Yen", "currency_code": "JPY"},
    {"country": "Jordan", "currency_name": "Jordanian Dinar", "currency_code": "JOD"},
    {"country": "Kazakhstan", "currency_name": "Kazakhstani Tenge", "currency_code": "KZT"},
    {"country": "Kenya", "currency_name": "Kenyan Shilling", "currency_code": "KES"},
    {"country": "Kiribati", "currency_name": "Australian Dollar", "currency_code": "AUD"},
    {"country": "Kuwait", "currency_name": "Kuwaiti Dinar", "currency_code": "KWD"},
    {"country": "Kyrgyzstan", "currency_name": "Kyrgyzstani Som", "currency_code": "KGS"},
    {"country": "Laos", "currency_name": "Lao Kip", "currency_code": "LAK"},
    {"country": "Latvia", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Lebanon", "currency_name": "Lebanese Pound", "currency_code": "LBP"},
    {"country": "Lesotho", "currency_name": "Lesotho Loti", "currency_code": "LSL"},
    {"country": "Liberia", "currency_name": "Liberian Dollar", "currency_code": "LRD"},
    {"country": "Libya", "currency_name": "Libyan Dinar", "currency_code": "LYD"},
    {"country": "Liechtenstein", "currency_name": "Swiss Franc", "currency_code": "CHF"},
    {"country": "Lithuania", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Luxembourg", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Madagascar", "currency_name": "Malagasy Ariary", "currency_code": "MGA"},
    {"country": "Malawi", "currency_name": "Malawian Kwacha", "currency_code": "MWK"},
    {"country": "Malaysia", "currency_name": "Malaysian Ringgit", "currency_code": "MYR"},
    {"country": "Maldives", "currency_name": "Maldivian Rufiyaa", "currency_code": "MVR"},
    {"country": "Mali", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    {"country": "Malta", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Marshall Islands", "currency_name": "US Dollar", "currency_code": "USD"},
    {"country": "Mauritania", "currency_name": "Mauritanian Ouguiya", "currency_code": "MRU"},
    {"country": "Mauritius", "currency_name": "Mauritian Rupee", "currency_code": "MUR"},
    {"country": "Mexico", "currency_name": "Mexican Peso", "currency_code": "MXN"},
    {"country": "Micronesia", "currency_name": "US Dollar", "currency_code": "USD"},
    {"country": "Moldova", "currency_name": "Moldovan Leu", "currency_code": "MDL"},
    {"country": "Monaco", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Mongolia", "currency_name": "Mongolian Tögrög", "currency_code": "MNT"},
    {"country": "Montenegro", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Morocco", "currency_name": "Moroccan Dirham", "currency_code": "MAD"},
    {"country": "Mozambique", "currency_name": "Mozambican Metical", "currency_code": "MZN"},
    {"country": "Myanmar", "currency_name": "Burmese Kyat", "currency_code": "MMK"},
    {"country": "Namibia", "currency_name": "Namibian Dollar", "currency_code": "NAD"},
    {"country": "Nepal", "currency_name": "Nepalese Rupee", "currency_code": "NPR"},
    {"country": "Netherlands", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "New Zealand", "currency_name": "New Zealand Dollar", "currency_code": "NZD"},
    {"country": "Nicaragua", "currency_name": "Nicaraguan Córdoba", "currency_code": "NIO"},
    {"country": "Niger", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    {"country": "Nigeria", "currency_name": "Nigerian Naira", "currency_code": "NGN"},
    {"country": "North Korea", "currency_name": "North Korean Won", "currency_code": "KPW"},
    {"country": "North Macedonia", "currency_name": "Macedonian Denar", "currency_code": "MKD"},
    {"country": "Norway", "currency_name": "Norwegian Krone", "currency_code": "NOK"},
    {"country": "Oman", "currency_name": "Omani Rial", "currency_code": "OMR"},
    {"country": "Pakistan", "currency_name": "Pakistani Rupee", "currency_code": "PKR"},
    {"country": "Palau", "currency_name": "US Dollar", "currency_code": "USD"},
    {"country": "Panama", "currency_name": "Panamanian Balboa", "currency_code": "PAB"},
    {"country": "Papua New Guinea", "currency_name": "Papua New Guinean Kina", "currency_code": "PGK"},
    {"country": "Paraguay", "currency_name": "Paraguayan Guaraní", "currency_code": "PYG"},
    {"country": "Peru", "currency_name": "Peruvian Sol", "currency_code": "PEN"},
    {"country": "Philippines", "currency_name": "Philippine Peso", "currency_code": "PHP"},
    {"country": "Poland", "currency_name": "Polish Zloty", "currency_code": "PLN"},
    {"country": "Portugal", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Qatar", "currency_name": "Qatari Riyal", "currency_code": "QAR"},
    {"country": "Romania", "currency_name": "Romanian Leu", "currency_code": "RON"},
    {"country": "Russia", "currency_name": "Russian Ruble", "currency_code": "RUB"},
    {"country": "Rwanda", "currency_name": "Rwandan Franc", "currency_code": "RWF"},
    {"country": "Saint Kitts and Nevis", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    {"country": "Saint Lucia", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    {"country": "Saint Vincent and the Grenadines", "currency_name": "East Caribbean Dollar", "currency_code": "XCD"},
    {"country": "Samoa", "currency_name": "Samoan Tala", "currency_code": "WST"},
    {"country": "San Marino", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Sao Tome and Principe", "currency_name": "São Tomé and Príncipe Dobra", "currency_code": "STN"},
    {"country": "Saudi Arabia", "currency_name": "Saudi Riyal", "currency_code": "SAR"},
    {"country": "Senegal", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    {"country": "Serbia", "currency_name": "Serbian Dinar", "currency_code": "RSD"},
    {"country": "Seychelles", "currency_name": "Seychellois Rupee", "currency_code": "SCR"},
    {"country": "Sierra Leone", "currency_name": "Sierra Leonean Leone", "currency_code": "SLE"},
    {"country": "Singapore", "currency_name": "Singapore Dollar", "currency_code": "SGD"},
    {"country": "Slovakia", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Slovenia", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Solomon Islands", "currency_name": "Solomon Islands Dollar", "currency_code": "SBD"},
    {"country": "Somalia", "currency_name": "Somali Shilling", "currency_code": "SOS"},
    {"country": "South Africa", "currency_name": "South African Rand", "currency_code": "ZAR"},
    {"country": "South Korea", "currency_name": "South Korean Won", "currency_code": "KRW"},
    {"country": "Spain", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Sri Lanka", "currency_name": "Sri Lankan Rupee", "currency_code": "LKR"},
    {"country": "Sudan", "currency_name": "Sudanese Pound", "currency_code": "SDG"},
    {"country": "Suriname", "currency_name": "Surinamese Dollar", "currency_code": "SRD"},
    {"country": "Sweden", "currency_name": "Swedish Krona", "currency_code": "SEK"},
    {"country": "Switzerland", "currency_name": "Swiss Franc", "currency_code": "CHF"},
    {"country": "Syria", "currency_name": "Syrian Pound", "currency_code": "SYP"},
    {"country": "Taiwan", "currency_name": "New Taiwan Dollar", "currency_code": "TWD"},
    {"country": "Tajikistan", "currency_name": "Tajikistani Somoni", "currency_code": "TJS"},
    {"country": "Tanzania", "currency_name": "Tanzanian Shilling", "currency_code": "TZS"},
    {"country": "Thailand", "currency_name": "Thai Baht", "currency_code": "THB"},
    {"country": "Timor-Leste", "currency_name": "US Dollar", "currency_code": "USD"},
    {"country": "Togo", "currency_name": "West African CFA Franc", "currency_code": "XOF"},
    {"country": "Tonga", "currency_name": "Tongan Paʻanga", "currency_code": "TOP"},
    {"country": "Trinidad and Tobago", "currency_name": "Trinidad and Tobago Dollar", "currency_code": "TTD"},
    {"country": "Tunisia", "currency_name": "Tunisian Dinar", "currency_code": "TND"},
    {"country": "Turkey", "currency_name": "Turkish Lira", "currency_code": "TRY"},
    {"country": "Turkmenistan", "currency_name": "Turkmenistan Manat", "currency_code": "TMT"},
    {"country": "Tuvalu", "currency_name": "Australian Dollar", "currency_code": "AUD"},
    {"country": "Uganda", "currency_name": "Ugandan Shilling", "currency_code": "UGX"},
    {"country": "Ukraine", "currency_name": "Ukrainian Hryvnia", "currency_code": "UAH"},
    {"country": "United Arab Emirates", "currency_name": "UAE Dirham", "currency_code": "AED"},
    {"country": "United Kingdom", "currency_name": "Pound Sterling", "currency_code": "GBP"},
    {"country": "United States", "currency_name": "US Dollar", "currency_code": "USD"},
    {"country": "Uruguay", "currency_name": "Uruguayan Peso", "currency_code": "UYU"},
    {"country": "Uzbekistan", "currency_name": "Uzbekistani Som", "currency_code": "UZS"},
    {"country": "Vanuatu", "currency_name": "Vanuatu Vatu", "currency_code": "VUV"},
    {"country": "Vatican City", "currency_name": "Euro", "currency_code": "EUR"},
    {"country": "Venezuela", "currency_name": "Venezuelan Bolívar", "currency_code": "VES"},
    {"country": "Vietnam", "currency_name": "Vietnamese Dong", "currency_code": "VND"},
    {"country": "Yemen", "currency_name": "Yemeni Rial", "currency_code": "YER"},
    {"country": "Zambia", "currency_name": "Zambian Kwacha", "currency_code": "ZMW"},
    {"country": "Zimbabwe", "currency_name": "Zimbabwean Dollar", "currency_code": "ZWL"}
]

def load_countries():
    for country in countries_currencies:
        Country.objects.create(
            name=country.get("country"),
            currency=country.get("currency_name"),
            currency_code=country.get("currency_code")
        )
        print(country)