# Generated by Django 5.2.5 on 2025-09-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceattendancemetric",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Both", "Both")],
                default="Both",
                max_length=20,
            ),
        ),
    ]
