# Generated by Django 5.2.5 on 2025-09-10 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("membership", "0017_serviceattendance_month_serviceattendance_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChurchMonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("month_name", models.CharField(max_length=255)),
                ("month_number", models.IntegerField()),
                ("year", models.IntegerField(default=2025)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branchmonthlyreports",
                        to="membership.branch",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
