# Generated by Django 5.2.5 on 2025-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="has_presbyter",
            field=models.BooleanField(default=False),
        ),
    ]
