# Generated by Django 5.2.5 on 2025-10-19 12:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0010_alter_kagdistrictmonthlyreport_pastor"),
        ("membership", "0011_remove_membergroup_chairperson_and_more"),
        ("sections", "0005_sectionreport_pastor_sectionreport_total_collected"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionreport",
            name="adult",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="children",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="church",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="church_support",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="church_welfare",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="district_missions",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="easter",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="general_fund",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="kagdom",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="kenya_kids",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="pastor",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="pastors_fund",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="pastors_tithe",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="presbyter_tithe",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="report",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="resource_mobilisation",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="special_offering",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="sunday_school",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="total_collected",
        ),
        migrations.AlterField(
            model_name="sectionreport",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="districts.district"
            ),
        ),
        migrations.AlterField(
            model_name="sectionreport",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sections.section"
            ),
        ),
        migrations.CreateModel(
            name="SectionMonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "general_fund",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "sunday_school",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "pastors_tithe",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "presbyter_tithe",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "easter",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "special_offering",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "kenya_kids",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "pastors_fund",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("month", models.CharField(max_length=255, null=True)),
                ("year", models.IntegerField(null=True)),
                (
                    "kagdom",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "district_missions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "resource_mobilisation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "church_support",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "church_welfare",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                ("children", models.IntegerField(default=0)),
                ("adult", models.IntegerField(default=0)),
                (
                    "total_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=100
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="membership.branch",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="districts.district",
                    ),
                ),
                (
                    "pastor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sections.sectionreport",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sections.section",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
