# Generated by Django 5.2.5 on 2025-10-19 18:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("districts", "0010_alter_kagdistrictmonthlyreport_pastor"),
        ("membership", "0011_remove_membergroup_chairperson_and_more"),
        ("sections", "0006_remove_sectionreport_adult_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionreport",
            name="adult",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="children",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="church",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="membership.branch",
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="church_support",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="church_welfare",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="district_missions",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="easter",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="general_fund",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="kagdom",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="kenya_kids",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="pastor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="pastors_fund",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="pastors_tithe",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="presbyter_tithe",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="districts.districtreport",
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="resource_mobilisation",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="special_offering",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="sunday_school",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AddField(
            model_name="sectionreport",
            name="total_collected",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=100
            ),
        ),
        migrations.AlterField(
            model_name="sectionreport",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districtsectionreports",
                to="districts.district",
            ),
        ),
        migrations.AlterField(
            model_name="sectionreport",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sections.section",
            ),
        ),
        migrations.DeleteModel(
            name="SectionMonthlyReport",
        ),
    ]
