# Generated by Django 5.2.5 on 2025-10-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0007_sectionreport_adult_sectionreport_children_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionreport",
            name="adult",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="children",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="church",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="church_support",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="church_welfare",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="district_missions",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="easter",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="general_fund",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="kagdom",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="kenya_kids",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="pastor",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="pastors_fund",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="pastors_tithe",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="presbyter_tithe",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="resource_mobilisation",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="special_offering",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="sunday_school",
        ),
        migrations.RemoveField(
            model_name="sectionreport",
            name="total_collected",
        ),
    ]
