# Generated by Django 5.2.5 on 2025-10-24 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sections", "0008_remove_sectionreport_adult_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionreport",
            name="month",
        ),
        migrations.CreateModel(
            name="SectionMonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("month", models.CharField(max_length=255, null=True)),
                ("year", models.IntegerField(null=True)),
                (
                    "section_report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sections.sectionreport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
